967 feature request authorization in the algorithm store
vantage6/vantage6 pull request #1033
Opened 2024-02-06 09:48 UTC by wbaccinelli

Fixes https://github.com/vantage6/vantage6/issues/967

2024-02-07 10:27 UTC, bartvanb commented
Cool to see your progress, looks nice! I changed the base branch to release/4.3 and this gives a couple of merge conflicts, let me know if you need help merging this. 

Also, I was wondering about the review tables - are you already planning to implement the review process as part of this PR? My preference would be to do that in a separate PR to avoid this one becoming bigger than it already is

2024-02-07 10:48 UTC, wbaccinelli commented
> Cool to see your progress, looks nice! I changed the base branch to release/4.3 and this gives a couple of merge conflicts, let me know if you need help merging this.
> 
> Also, I was wondering about the review tables - are you already planning to implement the review process as part of this PR? My preference would be to do that in a separate PR to avoid this one becoming bigger than it already is

@bartvanb Perfect! Yes, I will most probably need help with the merging.
No, I created the table, but I will not implement the endpoint. In this PR I am planning to have the endpoints implemented just for the algorithms and the users. Does this make sense?

2024-02-08 08:59 UTC, bartvanb commented
> No, I created the table, but I will not implement the endpoint. In this PR I am planning to have the endpoints implemented just for the algorithms and the users. Does this make sense?

Sounds good to me!

2024-02-14 14:41 UTC, bartvanb reviewed
Good progress! I'm happy to see that the code looks nice and am sure that we will be able to finish this up quite soon. Most of my comments are very minor (a lot of docstring things)

One thing was not yet entirely clear to me: how does the `id_server` parameter work? Is this an id of the server? Is this the id of the user on a server? And if so, where is that server defined and how does it work if multiple servers have access to the store?

2024-02-14 14:41 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/model/permission.py
> +# )
Maybe add a TODO to integrate this with the Permission model from the v6 server

2024-02-14 14:41 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/model/review.py
> +        List of users that belong to this role
Please update the docstring ;-)

2024-02-14 14:41 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/model/review.py
> +    reviewers = relationship("User", back_populates="reviews")
Should we also have a relationship to Algorithm?

2024-02-14 14:41 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/model/review.py
> +            f"reviewers: {self.reviewers}, "
Maybe just the IDs here? It would become a nightmare if the user class has a backref to these reviews, then the string representation would become an endless recursive loop if I'm not mistaken :-)

2024-02-14 14:41 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/model/role.py
> +        List of users that belong to this role
Docstring

2024-02-14 14:41 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/model/role.py
> +        :class:`.~vantage6.server.model.role.Role` | None
change class reference

2024-02-14 14:41 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/model/role_rule_association.py
> +)
Add TODO to refactor with server model as I think they're identical

2024-02-14 14:41 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/model/rule.py
> +    users : list[:class:`.~vantage6.server.model.user.User`]
Update refs

2024-02-14 14:41 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/model/rule.py
> +            Operation of the rule, e.g. 'view'
docstring

2024-02-14 14:41 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/model/user.py
> +        User id as saved in the V6 server
`username` attribute is missing

2024-02-14 14:41 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/model/user.py
> +    id_server = Column(Integer, unique=True)
How is this ID linked to the servers that are allowed to access this algorithm store? And how does it work with creating the initial root permissions when no server is linked yet?

2024-02-14 14:41 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/__init__.py
> +    return protection_decorator
Good that you refactored this!

2024-02-14 14:41 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/__init__.py
> +
Super neat that we can handle all these authorization checks in a single decorator, that keeps the endpoints much cleaner!

2024-02-14 14:41 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/__init__.py
> +                msg = f"This user is not allowed to perform this operation"
I'd say "You are not allowed to perform this operation" since it will be fed back to the user

2024-02-14 14:41 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/algorithm.py
> +        """Delete algorithm
Patch algorithm

2024-02-14 14:41 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/algorithm.py
> +        if (name := data.get('name')) is not None:
I totally missed that `:=` is a thing but looks nice.

Alternative is to use a for loop like [here](https://github.com/vantage6/vantage6/blob/main/vantage6-server/vantage6/server/resource/organization.py#L448)

2024-02-14 14:41 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/role.py
> +from vantage6.server.resource.common.pagination import Pagination
I'm pretty sure these server imports have moved now in the `release/4.3` branch

2024-02-14 14:41 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/role.py
> +                sign (-) in front of the field to sort in descending order.
docstring

2024-02-14 14:41 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/schema/output_schema.py
> +    return url_for(endpoint, **values)
Add TODO to remove duplicate code?

2024-02-15 13:39 UTC, wbaccinelli commented
> Good progress! I'm happy to see that the code looks nice and am sure that we will be able to finish this up quite soon. Most of my comments are very minor (a lot of docstring things)
> 
> One thing was not yet entirely clear to me: how does the `id_server` parameter work? Is this an id of the server? Is this the id of the user on a server? And if so, where is that server defined and how does it work if multiple servers have access to the store?

Thank you for the review! The code still needs to be cleaned up a bit:)
The user authentication is still a bit blurry, so, for now, the `id_server` parameter is the id of the user in the server. In this way the account on the server is linked to the user in the store. I agree, we should also link this to a specific server. I can add a reference to the whitelisted servers, so to make it unique, would that be an idea? I think that, in general, the authentication should be tackled in the future

2024-02-15 13:42 UTC, wbaccinelli commented on vantage6-algorithm-store/vantage6/algorithm/store/__init__.py
> +)
Absolutely agree on this! Once the feature works, I will try to reduce the duplications

2024-02-15 13:44 UTC, wbaccinelli commented on vantage6-algorithm-store/vantage6/algorithm/store/default_roles.py
> +# https://github.com/vantage6/vantage6/issues/53
Sure, if it's faster and you have time, go ahead. Otherwise, I can also take a look at how it was solved

2024-02-15 13:45 UTC, wbaccinelli commented on vantage6-algorithm-store/vantage6/algorithm/store/default_roles.py
> +        db.Rule.get_by_('algorithm', Operation.EDIT)
Yes, that's a very good idea. Will do

2024-02-15 13:50 UTC, wbaccinelli commented on vantage6-algorithm-store/vantage6/algorithm/store/default_roles.py
> +        db.Rule.get_by_('algorithm', Operation.CREATE)
You're right, I added a patch endpoint to the algorithm for this, and never assigned the permission 😅

2024-02-15 13:51 UTC, wbaccinelli commented on vantage6-algorithm-store/vantage6/algorithm/store/globals.py
> +}
Yes, that's way neater!

2024-02-15 13:53 UTC, wbaccinelli commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/algorithm.py
> +        if (name := data.get('name')) is not None:
Definitely more compact!

2024-02-16 09:18 UTC, bartvanb commented
> for now, the `id_server` parameter is the id of the user in the server. In this way the account on the server is linked to the user in the store. I agree, we should also link this to a specific server. I can add a reference to the whitelisted servers, so to make it unique, would that be an idea? I think that, in general, the authentication should be tackled in the future

Yes I think indeed linking it to a whitelisted server would be very useful! However then it will be difficult to create a first root user since there are no v6 servers linked at first algorithm store startup... maybe we should actually make that a configuration setting (for now) so that we can create an initial user with proper permissions

2024-02-28 16:48 UTC, bartvanb requested changes
I have done a second round of review and I'm quite happy with how this is getting along. All my comments are quite small. I haven't had time to test it yet but I'll do that tomorrow. 

There are a few things that ideally I'd like to add before releasing it in 4.3:
- Python client part for roles/rules/users in the algorithm store. If we have that, the store is a bit more usable than if we only offer the API.
- default roles: does anyone but root have access to add new users / edit their permissions? In that case, maybe we should make some extra default roles. Any thoughts?

Let's discuss who can do what. Maybe I can do the Python client part as that also allows me to test a lot of things.

Then I wrote down a couple of things that should be done at some point for these changes but not necessarily before releasing 4.3. Let's create separate issue(s) for those and work on them later.

Stuff for later:
- Function documentation
- Documentation about how authorization in algorithm store works (like [3.7. Permission management - vantage6 documentation](https://docs.vantage6.ai/en/main/server/permissions.html)
- refactoring parts that are duplicates or near duplicates of v6 server code (e.g. files like model/rule.py are I think nearly the same in server)
- unit tests
- Implement new endpoint PATCH /algorithm as `client.algorithm.update()` in Userclient
- Implement missing`/role` endpoints and `/role/rules` endpoints (fine if it’s missing now as the default roles pretty much cover all the options)
- Implement GET `rule/<id>` endpoint
- Implement option to assign single rules to a user
- If someone assigns a user permissions in the algorithm store, make sure that the user exists in that vantage6 server (yield error if not)

Also, all new endpoints, or new options in endpoints, should become available in the Python client.

2024-02-28 16:48 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/permission.py
> +        raise ValueError(f"Unknown operation {operation}")
Not sure if you actually use this function? If you don't, then remove it, otherwise I think `operation.REVIEW` is missing

2024-02-28 16:48 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/permission.py
> +    def _id_in_list(self, id_: int, resource_list: list[Base]) -> bool:
is this function used anywhere?

2024-02-28 16:48 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/__init__.py
> +                return {"msg": msg}, HTTPStatus.INTERNAL_SERVER_ERROR
I'd prefer a try/catch here - if you agree it would be nice to implement it, otherwise fine by me to leave it

2024-02-28 16:48 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/algorithm.py
> +        algorithm.save()
Nice that you implemented this endpoint! Looks nice and clean

2024-02-28 16:48 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/user.py
> +    pass
This should be removed

2024-02-28 16:48 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/user.py
> +        # TODO: add pagination
Is this difficult to add now? Then we should put it on a TODO list, otherwise we should implement now

2024-02-28 16:48 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/user.py
> +        # TODO: add pagination
I think I already added pagination to the algorithms right? In that case it should not be a lot of work

2024-02-28 16:48 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/user.py
> +            user.username = data["username"]
I think this whole option should be deleted: the username links to the username in the v6 server, so if it's changed here and not there, that's confusing (and in the v6 server I don't think you're allowed to edit the username)

2024-02-28 16:48 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/user.py
> +          Delete a user account permanently.\n
I would say "Unregister the vantage6 user account from the algorithm store"

2024-02-28 16:48 UTC, bartvanb commented on vantage6/vantage6/cli/configuration_wizard.py
> +    ).ask()
I think I mentioned it above, but I think if you're just requesting the ID *or* the username you have enough information (and you don't have the risk that id and username don't match). 
My preference would be to use usernames, but it's not very important because of course the authorization will be external in the future

2024-02-29 08:23 UTC, wbaccinelli commented
> I have done a second round of review and I'm quite happy with how this is getting along. All my comments are quite small. I haven't had time to test it yet but I'll do that tomorrow.

Thanks a lot @bartvanb! Let me know if something weird pops up during the testing.

> There are a few things that ideally I'd like to add before releasing it in 4.3:
> 
> * Python client part for roles/rules/users in the algorithm store. If we have that, the store is a bit more usable than if we only offer the API.
> * default roles: does anyone but root have access to add new users / edit their permissions? In that case, maybe we should make some extra default roles. Any thoughts?

You are right, at the moment it's just the root. I think that it would maybe make sense to let all the roles create and edit profiles? They cannot assign permissions that they don't have anyway and it would make sense that a developers appoints another developer or that a reviewer appoints another reviewer..

> Let's discuss who can do what. Maybe I can do the Python client part as that also allows me to test a lot of things.

I can take care of the roles and I'm totally happy with you looking into the client :)

> Then I wrote down a couple of things that should be done at some point for these changes but not necessarily before releasing 4.3. Let's create separate issue(s) for those and work on them later.
> 
> Stuff for later:
> 
> * Function documentation
> * Documentation about how authorization in algorithm store works (like [3.7. Permission management - vantage6 documentation](https://docs.vantage6.ai/en/main/server/permissions.html)
> * refactoring parts that are duplicates or near duplicates of v6 server code (e.g. files like model/rule.py are I think nearly the same in server)
> * unit tests
> * Implement new endpoint PATCH /algorithm as `client.algorithm.update()` in Userclient
> * Implement missing`/role` endpoints and `/role/rules` endpoints (fine if it’s missing now as the default roles pretty much cover all the options)

I will open these new issues (definitely they need to be tackled).

2024-02-29 08:26 UTC, wbaccinelli commented on vantage6-algorithm-store/vantage6/algorithm/store/__init__.py
> +                        id_server=id_server, v6_server_id=v6_server.id
I think that it's a very good idea. It is used somewhere, but it's not a problem at all to swap to the username and it makes things neater.

2024-02-29 08:29 UTC, wbaccinelli commented on vantage6-algorithm-store/vantage6/algorithm/store/globals.py
> +RESOURCES = ["version", "algorithm", "vantage6_server", "role", "user"]
I agree, it's quite impractical. I will most probably add a TODO for now.

2024-02-29 09:06 UTC, wbaccinelli commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/user.py
> +        # TODO: add pagination
Sure, I can add the pagination already!

2024-02-29 09:08 UTC, wbaccinelli commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/user.py
> +            user.username = data["username"]
Yes, absolutely right, and this goes very well together with changing from id to username as mentioned in a previous comment.

2024-02-29 09:09 UTC, wbaccinelli commented on vantage6/vantage6/cli/configuration_wizard.py
> +    ).ask()
Totally agree

2024-02-29 09:15 UTC, wbaccinelli commented on vantage6-algorithm-store/vantage6/algorithm/store/model/rule.py
> +    operation = Column(Enum(Operation))
Oh, that's good to know. Let's leave it open to the possibility of adding new operations, indeed. I will change the `Enum` then.

2024-02-29 09:19 UTC, wbaccinelli commented on vantage6-algorithm-store/vantage6/algorithm/store/permission.py
> +        raise ValueError(f"Unknown operation {operation}")
There is one place where it is used for giving a message, but it can be easily replaced, to be true. I will just delete it

2024-02-29 09:24 UTC, wbaccinelli commented on vantage6-algorithm-store/vantage6/algorithm/store/permission.py
> +    def _id_in_list(self, id_: int, resource_list: list[Base]) -> bool:
Nope, I'm removing it.

2024-02-29 09:26 UTC, wbaccinelli commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/__init__.py
> +                return {"msg": msg}, HTTPStatus.INTERNAL_SERVER_ERROR
No problem in changing to try/catch!

2024-03-04 15:25 UTC, bartvanb commented
As discussed earlier, today I added a few commits to add functionality for roles/rules/users management of the algorithm store to the Python client. I also did a few other things:

- Added GET `/rule` endpoint. This was necessary to do now as the `/role` endpoint could not complete without it (error in linking schemas)
- New configuration option to make the endpoints to view algorithms open to either everyone, or all users from whitelisted servers. This way an algorithm store admin can control if the algorithms are open to everyone without the need for authentication
- Added a few more bullet points to the 'implement later' section above.
- Minor bugfixing.

So while developing the Python client part I was also able to test how it works and I am happy with this as a first version.

2024-03-06 14:40 UTC, bartvanb approved these changes

2024-03-06 14:41 UTC, merged