Added allowed_algorithms to configuration wizard and add warning mess…
vantage6/vantage6 pull request #1046
Opened 2024-02-15 10:57 UTC by bartvanb

…ages if it is not defined

To prevent the configuration wizard from becoming to long, we may remove the VPN configuration option by default (as not many people use that)

2024-03-06 09:37 UTC, frankcorneliusmartin commented on vantage6/vantage6/cli/configuration_wizard.py
> +        info("^harbor2\.vantage6\.ai/demo/average    Allow the demo average algorithm")
Maybe also add an example by pinning a specific hash

2024-03-06 09:38 UTC, frankcorneliusmartin commented on vantage6/vantage6/cli/configuration_wizard.py
> +            algo = q.text(message="Enter your algorithm expression:").ask()
I would make this `regex`

2024-03-06 09:38 UTC, frankcorneliusmartin commented on vantage6/vantage6/cli/configuration_wizard.py
> +                "Do you want to add another algorithm?", default=True
Do you want to add another regex. As one regex does not neccasaraly mean one algorithm

2024-03-06 09:42 UTC, frankcorneliusmartin reviewed
Can you also address this message, this log has been replaced by logging in the `_setup_policies`

2024-03-06 09:43 UTC, frankcorneliusmartin requested changes
Minor changes

2024-03-06 14:11 UTC, bartvanb commented on vantage6/vantage6/cli/configuration_wizard.py
> +        info("^harbor2\.vantage6\.ai/demo/average    Allow the demo average algorithm")
Done

2024-03-06 14:13 UTC, bartvanb commented on vantage6/vantage6/cli/configuration_wizard.py
> +            algo = q.text(message="Enter your algorithm expression:").ask()
Since I also added functionality to explicitly support normal strings now, I will leave it at `expression`

2024-03-06 14:13 UTC, bartvanb commented on vantage6/vantage6/cli/configuration_wizard.py
> +                "Do you want to add another algorithm?", default=True
See above, I changed this into `algorithm expression` now

2024-03-06 15:02 UTC, frankcorneliusmartin commented on vantage6/vantage6/cli/configuration_wizard.py
> +            algo = q.text(message="Enter your algorithm expression:").ask()
Ah I see now. However I dont think your `_is_regex_pattern` method is correct?

```python
>>> pat = "henk*"
>>> re.match(pat, pat)
<re.Match object; span=(0, 4), match='henk'>
>>> not re.match(pat, pat)
False
>>> pat = "^henk*"
>>> not re.match(pat, pat)
True
```

A regular string is also a regex pattern so how would you be able to distinguish between them? You could assume that when it does not contain any special regex chars it is a regular string, but then you are still not sure. Maybe add the type to the config / questionary?

Or does it make sense to make these assumptions?

2024-03-07 10:51 UTC, bartvanb commented on vantage6/vantage6/cli/configuration_wizard.py
> +            algo = q.text(message="Enter your algorithm expression:").ask()
I prefer not to add it to the questionaire, so as not to complicate the questionaire further. Maybe it would be possible to add it as a configuration setting. 

For now, I have improved the implementation of checking regexes and also that of converting string to regex

2024-03-07 10:58 UTC, frankcorneliusmartin approved these changes

2024-03-11 11:01 UTC, merged