Feature/studies
vantage6/vantage6 pull request #1069
Opened 2024-02-28 13:32 UTC by bartvanb

Fix #812

2024-03-06 10:21 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/model/study.py
> +            f"{self.id}: '{self.name}', "
Also mention the `collaboration_id` (although I dont think we use these representations any more as we dont use the shell? Maybe delete these in the future?)
```suggestion
            "<Study "
            f"{self.id}: '{self.name}', "
            f"part of collaboration: {self.collaboration_id}, "
            f"{number_of_organizations} organization(s), "
            f"{number_of_tasks} task(s)"
            ">"
```

2024-03-06 10:23 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/model/study.py
> +    collaborate on a particular substudy. Studies use the same nodes and data
I would not call this *substudy* but just *study*.

2024-03-06 13:11 UTC, frankcorneliusmartin requested changes

2024-03-06 13:11 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/study.py
> +        if not study:
Unlikely but not impossible? I think there might be servers that do not use the study concept at all? I think best to check first if an `id` has been given and then if there is no study. 

```suggestion
        if id and not study:
```

In case en empty list is returned (when no `id` has been specified) seems valid to me. Now the users will get an error that the `id=None` does not exist.

2024-03-06 13:11 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/study.py
> +            return {"msg": str(e)}, HTTPStatus.BAD_REQUEST
Shouldnt this be an `INTERNAL_SERVER_ERROR` (500)?

2024-03-06 14:43 UTC, bartvanb commented on vantage6-server/vantage6/server/model/study.py
> +            f"{self.id}: '{self.name}', "
I guess we use them sometimes in debugging (at least I do), it's useful to me if `print(study)` gives me some nice info

2024-03-06 14:45 UTC, bartvanb commented on vantage6-server/vantage6/server/model/study.py
> +            f"{self.id}: '{self.name}', "
I added this btw

2024-03-06 14:46 UTC, bartvanb commented on vantage6-server/vantage6/server/model/study.py
> +    collaborate on a particular substudy. Studies use the same nodes and data
I replaced it now by 'research question' as explaining the study concept with the exact same wording doesn't seem to be most clear to me

2024-03-06 14:46 UTC, bartvanb commented on vantage6-server/vantage6/server/model/study.py
> +        List of tasks that are part of this collaboration
I knew I must have missed this somewhere :-)

2024-03-06 14:48 UTC, bartvanb commented on vantage6-server/vantage6/server/model/member.py
> +Member table.
I changed it to "A study is a subset of organizations that form a collaboration"

2024-03-06 15:37 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/study.py
> +    def _check_membership_collaboration(
I can imagine that it may end up there, but at this moment it doesn't make sense to have it there, because one of the places that this function is called is in POST /study: in that case the SQL model is not created yet so we cannot use it from the model class.

2024-03-06 15:42 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/task.py
> +        collaboration = db.Collaboration.get(collaboration_id)
It is actually not either/or: if both collaboration and study ID are defined that is also OK (in that case we do verify that the specified study is part of the specified collaboration). I clarified this in the TaskInputSchema docsstring

I did move some things into the if statements as I was redefining some things after the `if` and it looked cleaner when everything was inside the `if`.

2024-03-06 15:43 UTC, bartvanb commented on docs/server/permissions.rst
> +* ``@only_for(('user', 'container')``: only accessible to users and algorithm
Well noticed!

2024-03-06 15:45 UTC, bartvanb commented on vantage6-algorithm-tools/vantage6/algorithm/client/__init__.py
> +            id: int
Wow long time since I've seen this mistake :looks angrily at Copilot:

2024-03-06 15:49 UTC, bartvanb commented on vantage6-client/vantage6/client/__init__.py
> +            delete_dependents : bool, optional
No it will actually refuse to remove the collaboration and return a 400 status (except if there are no dependents in the DB). We chose to do it that way to prevent having dangling tasks, or worse: when the last collaboration is deleted, and a new collaboration is created, it will have the same ID and that may cause unauthorized access.

I clarified the docstring so that it is clear what will happen.

2024-03-06 15:53 UTC, bartvanb commented on vantage6-client/vantage6/client/__init__.py
> +            return id_
Good suggestion, I implemented something very close to this

2024-03-06 15:54 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/study.py
> +        return org_schema.dump(study.organizations, many=True), HTTPStatus.OK
We are actually returning the organizations that are left in the study. I implemented it this way because it is the same as in the endpoints where organizations are added to/deleted from a collaboration.

If we change it here, we should change it in both

2024-03-06 15:58 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/study.py
> +        if not study:
This was an old, now irrelevant comment that arised because I copied the endpoints from `/collaboration` and then modified them to become the study endpoints. I now removed the 'unlikely to happen without ID' from both. An id is always specified in GET requests (otherwise it doesn't find its way to this endpoint).

It is indeed possible at present that ID is not a valid positive integer - we should do input schema validation on GET and DELETE requests as well (it's currently only for PATCH and POST). There is already an issue for this somewhere.

2024-03-06 16:01 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/study.py
> +            return {"msg": str(e)}, HTTPStatus.BAD_REQUEST
I agree. Note that this is a code block that is currently in a lot of endpoints, so I'll change it in all of them

2024-03-06 16:02 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/study.py
> +            return {"msg": str(e)}, HTTPStatus.BAD_REQUEST
Note that I havent added the 500 to the docstrings (yet) as I think that this should actually never occur

2024-03-06 16:31 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/__init__.py
> +            delete_dependents : bool, optional
Sorry I worded that wrong, thanks for adding it

2024-03-06 16:33 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/study.py
> +        return org_schema.dump(study.organizations, many=True), HTTPStatus.OK
I am not against it but I think it is cleaner to return a message rather than the organizations left.

2024-03-06 16:38 UTC, frankcorneliusmartin approved these changes
Have a look at my last comments and do with them what you want ;-).

2024-03-07 09:52 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/task.py
> +        collaboration = db.Collaboration.get(collaboration_id)
I now clarified this by 1) adding an extensive comment to explain this to the reader and 2) updating the API docs for these options so that it is also clear there.
I preferred this over `if/elif` because that would complicate the logic

2024-03-07 09:52 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/study.py
> +        return org_schema.dump(study.organizations, many=True), HTTPStatus.OK
I'll create an issue

2024-03-07 10:41 UTC, merged