Add algo stores to server from config
vantage6/vantage6 pull request #1156
Opened 2024-03-20 14:08 UTC by bartvanb

This PR makes sure that when config contains:

```
algorithm_stores:
  - name: Community store
    url: https://store.cotopaxi.vantage6.ai
```

That the community store will be available for all collaborations in that server

2024-03-22 10:24 UTC, wbaccinelli requested changes
Looks very nice! 
I put a few minor comments, and I have two highlights: 
- I have just a doubt about the concept of having the server whitelisting themselves, because it sounds like bypassing the check of the store admin. 
- I get now an error that I reported in the comments. I'm requesting the change just for this one (if it's not a mistake that I am making)

2024-03-22 10:24 UTC, wbaccinelli commented on vantage6-server/vantage6/server/__init__.py
> +        server_url = self.ctx.config.get("server_url")
We should change [this](https://github.com/vantage6/vantage6/blob/0272a09306c95bd5ec4d2556fc0de0247345f7e3/vantage6-algorithm-store/vantage6/algorithm/store/resource/__init__.py#L70) in the algorithm store, otherwise the `server_url` has to end with `/api`

2024-03-25 13:00 UTC, bartvanb commented on vantage6-server/vantage6/server/algo_store_communication.py
> +    )
Fully agree, in general this is not what you want. My thoughts are that the following changes should be made
- if store is not open to everyone, it should be implemented that only store owners can whitelist the server
- if algorithms in store are open to everyone, servers do not need to be whitelisted at the store (unless their users need permissions to manage the store). Instead, there should be some option at the server side to whitelist stores as 'read-only' or so, to indicate which stores are meant to be used by which collaborations
- Note that we should also *always* prevent localhost servers from being whitelisted on non-localhost stores and vice versa - that will just never work

If you agree, let's create an issue to tackle these things separately.

2024-03-25 13:13 UTC, bartvanb commented on vantage6-server/vantage6/server/algo_store_communication.py
> +            records_to_delete = existing_algorithm_stores
You are absolutely correct. These permissions are checked in a different place, i.e. the POST /algorithmstore endpoint. They are not part of the function here as that is also called at server startup time - I am assuming that the person deploying the server has permission to do this, which I think is a valid assumption because they would also be able to directly access the database and make changes there without going through the application

2024-03-25 13:19 UTC, bartvanb commented on vantage6-server/vantage6/server/algo_store_communication.py
> +        ).replace("127.0.0.1", "host.docker.internal")
If I'm not mistaken (which I very well might be), on Linux there would be no need to replace `localhost` or `127.0.0.1` because the localhost address would resolve to the host localhost address so the first attempt would work. This is of course assuming the container is connected to the host network but that should anyway be the case for v6 servers. 
What do you think?

2024-03-25 13:24 UTC, bartvanb commented on vantage6-server/vantage6/server/algo_store_communication.py
> +        params = param_dict
Uhmm it appears that indeed this would be possible with current setup :"-) Let's create an issue to fix that in a next patch release
(note that the code that you're reviewing here is also in the current implementation, I just moved it to another file now but it's practically the same)

2024-03-25 13:34 UTC, bartvanb commented on vantage6-server/vantage6/server/__init__.py
> +        server_url = self.ctx.config.get("server_url")
I think the `server_url` in the config file *should* contain `/api` - this was at least the choice I made when we released for v4.3.
But I agree it's nicer if it doesn't have to contain the API path, so I'll change that. Note that I've added something extra to ensure it is backwards compatible with v4.3

2024-03-26 08:10 UTC, wbaccinelli commented on vantage6-server/vantage6/server/algo_store_communication.py
> +    )
Sounds perfect!

2024-03-26 08:39 UTC, wbaccinelli commented on vantage6-server/vantage6/server/algo_store_communication.py
> +        ).replace("127.0.0.1", "host.docker.internal")
I think that you're right, I admit that I didn't check deeply. I had in mind that [here](https://github.com/vantage6/vantage6/blob/bc4f61051b30b20d3e8d0c18402dd9aafbd1a610/vantage6-algorithm-store/vantage6/algorithm/store/resource/__init__.py#L79) we had to define a `host_url` to connect to the server from the algorithms store in case of localhost, to make it possible to use `host.docker.internal` for WIndows and `172.17.0.1` for Linux. Can we maybe get rid of it also from the store? I haven't tested myself.

2024-03-26 08:54 UTC, wbaccinelli commented on vantage6/vantage6/cli/configuration_wizard.py
> +            {"name": "Community store", "url": "https://store.cotopaxi.vantage6.ai"}
Oh that's nice!

2024-03-27 08:20 UTC, wbaccinelli approved these changes
Works perfectly!

2024-03-28 16:04 UTC, bartvanb commented on vantage6-server/vantage6/server/algo_store_communication.py
> +    )
Just created #1177

2024-03-28 16:08 UTC, bartvanb commented on vantage6-server/vantage6/server/algo_store_communication.py
> +        ).replace("127.0.0.1", "host.docker.internal")
You're right, I'll add the same configuration option `['dev']['host_uri']` to the server so that it's consistent

2024-03-28 16:26 UTC, bartvanb commented on vantage6-server/vantage6/server/algo_store_communication.py
> +        params = param_dict
#1178

2024-03-29 08:10 UTC, wbaccinelli approved these changes
I added just a very last comment :)

2024-03-29 08:10 UTC, wbaccinelli commented on vantage6-server/vantage6/server/algo_store_communication.py
>          ).replace("127.0.0.1", "host.docker.internal")
I think that this should then be changed like this 

```suggestion
        algo_store_url = algo_store_url.replace(
            "localhost", host_uri
        ).replace("127.0.0.1", host_uri)
```

2024-04-04 09:07 UTC, bartvanb commented on vantage6-server/vantage6/server/algo_store_communication.py
>          ).replace("127.0.0.1", "host.docker.internal")
Ha thanks for spotting, that was a rather stupid mistake :-)

2024-04-04 11:27 UTC, merged