Feature/sessions
vantage6/vantage6 pull request #1247
Opened 2024-05-07 12:20 UTC by frankcorneliusmartin

Implements #943 

- [ ] Unittests
- [ ] User documentation

2024-08-22 13:49 UTC, bartvanb requested changes
Interesting stuff. As expected, quite a few comments. Most are smallish, I think I'm mostly tripping over a few names (especially 'handle') and don't understand everything yet. I also haven't tried running anything.

I'll also do a small commit fixing some spelling errors

2024-08-22 13:49 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/task.py
> +            databases = []
`data.get("databases", [])` :-)

2024-08-22 13:49 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/task.py
> +        # However they can also be user defined, although this has no use case yet.
I cannot really imagine this use case - this is something that should always be handled internally as it's rather complex. I suggest removing the option.

2024-08-22 13:49 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/common/input_schema.py
> +            allowed_keys = {"label", "type"}
Should `type` not always be present in the new setup? I think that's either the traditional type (csv/..) or dataframe?

2024-08-22 13:49 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/task.py
> +        )
I think this may be a merge issue - now you are adding this event while I think it was removed in the latest main branch. At least reading this it no longer seems to make sense as a `new_task` event is also sent a bit below here

2024-08-22 13:49 UTC, bartvanb commented on vantage6-server/tests_server/test_resource_session.py
> +        conf = data["config"][0]
I think you mention this already in the PR, but unittests should be extended to include permission checks and also the dataframes/columns etc.

2024-08-22 13:49 UTC, bartvanb commented on vantage6-server/tests_server/test_resource_session.py
> +        node = Node.get_by_api_key("123e4567-e89b-12d3-a456-426614174000")
Where does this magic value come from?

2024-09-11 07:50 UTC, frankcorneliusmartin commented on docs/features/algorithms/fig.plantuml
> +@enduml
You are right, this file is not used. It is used to copy from, this figure is with one of the rest files. I will remove it.

2024-09-11 07:54 UTC, frankcorneliusmartin commented on docs/features/algorithms/sessions.rst
> +    Task "0" - "1" DataFrame
Task - Dataframe. 0 - 1 is correct. This relationship is only set when a dataframe is modified. The use of the dataframes is still set though the databases key. The data extraction process could use multiple databases to construct a single dataframe, however this is an unlikely senario.

I will try to make the lines a little longer.

2024-09-11 08:41 UTC, frankcorneliusmartin commented on docs/features/algorithms/sessions.rst
> +``client.dataframe.create()`` methods and ``client.dataframe.preprocess()`` methods.
The idea is that session can be used by several tasks. In order to control the workflow of the user and permissions of the algorithm containers per different action we needed to create an additional endpoints. Or we could have abused the `/task` endpoint.

So when you hit the `/session` endpoint it means the users is initializing a new dataframe, to be used by real analysis tasks. So the data retrieval and preprocessing has been seperated from the federated analaysis parts. On the nodes they rely on the same mechanic. Containers that are started on user request. However depending on the endpoint the user triggers the container is assigned a different action. This different action is then linked to different permissions on the node. For example, only data extraction steps have access to the original data source.

2024-09-11 08:42 UTC, frankcorneliusmartin commented on docs/features/algorithms/sessions.rst
> +``client.dataframe.create()`` methods and ``client.dataframe.preprocess()`` methods.
Could you reread the first paragraphs of this page (inc figures) and see if this then makes more sense?

2024-09-11 08:45 UTC, frankcorneliusmartin commented on docs/features/algorithms/sessions.rst
> +
I agree, however since the docs are minimal now I created a new issue to pick this up when we are a little closer to release. See issue: https://github.com/vantage6/vantage6/issues/1469

2024-09-11 08:49 UTC, frankcorneliusmartin commented on docs/features/algorithms/sessions.rst
> +        not dependant on (4) as in this case (7) was requested after (4) was completed.
I am not sure what you mean. But in a single session there can be multiple dataframes. A pre-processing task can only modify a single dataframe. To help users we can provide visuals (maybe some sort of tree view) to help them understand what has happend to a certain dataframe.

2024-09-11 08:53 UTC, frankcorneliusmartin commented on docs/features/algorithms/sessions.rst
> +``parquet-tools show state.parquet``.
Yes I agree, I mostly put it here now for us. I opened an seperate issue for this: https://github.com/vantage6/vantage6/issues/1470

2024-09-11 08:55 UTC, frankcorneliusmartin commented on docs/features/algorithms/sessions.rst
> +related to sessions. For example, when you need to store a secret key that is used in a
Its is the same way that the `TEMPORARY_FOLDER` is used now. As long as https://github.com/vantage6/vantage6/issues/154 is not impemented I would like to keep this as an option. Just to keep the same features available as in v4.

2024-09-11 09:13 UTC, frankcorneliusmartin commented on docs/introduction/introduction.rst
> +    Session "1" -- "n" DataFrame
New issue: https://github.com/vantage6/vantage6/issues/1471

2024-09-11 09:29 UTC, frankcorneliusmartin commented on docs/release_notes.rst
> +4.6.1
I guess I branch of 4.6.x when it was not yet merged into `release/5.0`. This change is now no longer visible as it has been merged now.

2024-09-11 09:36 UTC, frankcorneliusmartin commented on vantage6-algorithm-store/vantage6/algorithm/store/_version.py
> +version_info = (4, 6, 1, "final", __build__, 0)
Same for this one. base branch was updated so this change is no longer visible in this PR

2024-09-11 09:43 UTC, frankcorneliusmartin commented on vantage6-algorithm-tools/vantage6/algorithm/decorator/action.py
> +    Check if the requested action matches the container action.
I added a longer description, hope it is more clear now.

2024-09-11 09:51 UTC, frankcorneliusmartin commented on vantage6-algorithm-tools/vantage6/algorithm/tools/decorators.py
> +            # TODO FM 24-07-2024 uncomment this
This is not the due date, this is the date the comment has been written.. However... this indeed should have been uncommented. Thanks :)

2024-09-12 12:03 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/subclients/dataframe.py
> +    @post_filtering(iterable=False)
Yes, so this was a bit of a hack solution when filtering at the API was not possible yet. We should probably remove the `filter` parameter from all client functions. 

In the future we probably also want the server to handle the `fields` argument, this could potentially safe a lot of traffic.

2024-09-12 12:06 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/subclients/dataframe.py
> +class DataFrameSubClient(ClientBase.SubClient):
I added a slightly modified version of what Bart suggested in the `ClientBase.SubClient` class.

2024-09-12 12:24 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/subclients/dataframe.py
> +        """Create a new data frame."""
Sorry all the docstring in this subclass where missing. I updated the docstring, hope it is more clear now what the different methods do.

2024-09-12 12:28 UTC, frankcorneliusmartin commented on docs/conf.py
> +autosummary_generate = False  # Turn on sphinx.ext.autosummary
This created an infinite loop for me. Ill sit down with you to see how you set this up. I rolled back this change.

2024-09-12 12:32 UTC, frankcorneliusmartin commented on docs/features/algorithms/sessions.rst
> +        not dependant on (4) as in this case (7) was requested after (4) was completed.
Currently we do not keep track of the last modification task on the computation task, if that is what you want?

2024-09-12 12:34 UTC, frankcorneliusmartin commented on docs/features/algorithms/sessions.rst
> +related to sessions. For example, when you need to store a secret key that is used in a
I fixed the 'hoofdzin' issue as you suggested.

2024-09-12 12:43 UTC, frankcorneliusmartin commented on vantage6-algorithm-tools/vantage6/algorithm/decorator/action.py
> +        result = func(*args, **kwargs)
I agree that we should create a possibility to create simple sessions. However I do not want to exclude custom CSV, Excel or Parquet handling. I think there should always be an option to write a custom adapter. 

We definitely should provide these basic adapters, and we add the concept "Simple Session" which you can check if you are creating a new session. 

I created a separate issue for this: https://github.com/vantage6/vantage6/issues/1477

2024-09-12 12:45 UTC, frankcorneliusmartin commented on vantage6-algorithm-tools/vantage6/algorithm/decorator/action.py
> +        result = func(*args, **kwargs)
Yes, however it is supplied by the `@data` decorator and not this. This was an outdated mental note for me. I removed it. 

See for example the tester I created: https://github.com/frankcorneliusmartin/v6-csv-extractor-py/blob/main/v6-csv-extractor-py/partial.py

2024-09-12 12:47 UTC, frankcorneliusmartin commented on vantage6-algorithm-tools/requirements.txt
> +pyarrow==16.1.0
Done, I made them `>=`

2024-09-12 13:55 UTC, frankcorneliusmartin commented on vantage6-algorithm-tools/vantage6/algorithm/tools/decorators.py
I refactored. All decorators are now in the folder in separate files. Note that algorithms need to change the import from `decorators` to `decorator`:

`from vantage6.algorithm.decorator import data`

2024-09-12 13:57 UTC, frankcorneliusmartin commented on vantage6-algorithm-tools/vantage6/algorithm/tools/decorators.py
> +                    "Exiting..."
This is the check. We only know the type once we really start the container, every check before that is a meta check. Which we *should* also do. In the UI we can assign every function with a type (data-extraction, preprocess, etc) and only show the users the methods that are applicable in that step. 

So you only get this error if you have started a method that does not perform the right action. E.g. when you try to extract data with a preprocessing function. 

I updated the error to be more clear.

2024-09-16 10:00 UTC, frankcorneliusmartin commented on vantage6-algorithm-tools/vantage6/algorithm/tools/decorators.py
> +                info("Reading Dataframe")
Done

2024-09-16 10:02 UTC, frankcorneliusmartin commented on vantage6-algorithm-tools/vantage6/algorithm/tools/util.py
> +    Get the action of the container.
I am very disappointed in Copilot..

2024-09-16 12:20 UTC, frankcorneliusmartin commented on vantage6-algorithm-tools/vantage6/algorithm/tools/wrappers.py
> +    Enum for the different file based database types.
Yes you are right. I adjusted the docstring.

2024-09-16 12:25 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/rich/table.py
> +    table.add_column("Column Name", justify="left", no_wrap=True)
You are right to be scared. It will show a bunch of vertical lines. I have no solution for this, we could cut it off at 10 columns and add some sort of ellipsis?

2024-09-16 12:56 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/rich/table.py
> +            )
I am confused? This error is send to the user. `Console.print` prints to the attached console or notebook or wathever?

2024-09-16 13:05 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/rich/table.py
> +    table.add_column("Dataframe")
I agree. However, we might want to customize each column with styling at a later point (see for example `rich_dataframe_schema_table`. And adding the function code would add just as much lines of code. So I rather not do it at the current time.

2024-09-16 13:05 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/rich/table.py
> +    table.add_column("Dataframe")
However if you insist, I post the code to do this already here: 

```python

def _add_columns(table: Table, columns: list[dict]) -> None:
    """
    Add multiple columns to a rich table.

    Parameters
    ----------
    table : Table
        Rich table object
    columns : list[str]
        List of columns names to add to the table.

    Examples
    --------
    This will add columns to a rich table.

    ```python
    table = Table()
    columns = ["column1", "column2"]
    _add_columns(table, columns)
    ```
    """
    for column in columns:
        table.add_column(column["name"])
```

2024-09-16 13:08 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/rich/table.py
I felt these functions are: experimental, specifically focused on visualization, can be used in multiple subclients. I would want to keep them separate for now.

2024-09-16 13:10 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/rich/table.py
I created a separate issue for this.

2024-09-16 13:14 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/subclients/dataframe.py
> +        pass
https://github.com/vantage6/vantage6/issues/1476

2024-09-16 13:20 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/subclients/session.py
> +            ``collaboration``, ``organization`` and ``own``.
Good one I had to look it up as well. I added it to the docstring: `own` is the answer.

2024-09-16 13:23 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/subclients/session.py
> +            Print the result in a table
There where many places. I updated it.

2024-09-16 13:25 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/subclients/session.py
> +        List of sessions
You are right. That is a wrong docstring. I updated it, hopefully its more clear now.

2024-09-16 14:12 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +        db_session.commit()
I agree. I made the `Column.clear()` method for this purpose.

2024-09-16 14:23 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/subclients/session.py
> +        # TODO FM 02-08-2024: This needs to be cleaned
Made a separate issue for this.

2024-09-16 14:25 UTC, frankcorneliusmartin commented on vantage6-common/vantage6/common/enum.py
> +    # TODO FM 26-07-2024: rename to finished_statuses
Thank you for the reminder. Done.

2024-09-16 14:27 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/docker_manager.py
> +            action=action,
Yes this looks ridicules. I made a separate issue, so we can resolve this after the merge.

2024-09-16 14:38 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/docker_manager.py
> +        while not (task.status == RunStatus.ACTIVE) and attempts < 3:
It should not be called task.. So actually the `RunStatus` is correct and the `TaskStatus` is wrong. I refactored that for the enums so we could create different status for the two entities. TaskStatus is now a status of a collection of runstatusses. I think we should indeed refactor everything to run in the node. 

However lets do that after @hcadavid and @frankcorneliusmartin (me) have merged. Else the mess would be bigger. I made a separate issue for it: https://github.com/vantage6/vantage6/issues/1484

2024-09-16 14:43 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/task_manager.py
> +        self.tmp_folder = "/mnt/tmp"
I dont want to remove them in this PR as there are several things I want to check before I do. I added a separate issue for checking all `v5+` todos. Then this should also be picked up.

2024-09-16 14:47 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/task_manager.py
> +        container. Otherwise, return an empty byte string.
The `DockerTaskManager` is agnostic to what kind of container he gets back at this point. We could refactor the function bellow, but its not super long and I kind-a like it the way it is as it makes very clear what happens for each different action.

2024-09-16 14:50 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/task_manager.py
> +            # Overwrite the session table
You are right. It creates or overwrites. Updated the comment.

2024-09-16 14:51 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/task_manager.py
> +            self.log.exception(f"Error writing status to state parquet file")
Haha lol. Yes I messed up and swapped them. Thanks.

2024-09-16 14:51 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/task_manager.py
> +            self.log.exception("Error writing session data to parquet file")
Yes

2024-09-20 10:04 UTC, bartvanb commented on vantage6-client/vantage6/client/subclients/dataframe.py
> +            Whether to print the data frame details. By default False.
I made changes in this PR that are also releveant here: https://github.com/vantage6/vantage6/pull/1492. Can you also make sure you have all the `@post_filtering` options and their docstrings as in the rest of the Python client?

2024-09-23 14:26 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/subclients/dataframe.py
> +            Whether to print the data frame details. By default False.
Why not merge it in here?

2024-09-23 14:48 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/model/dataframe.py
> +            ]
The `last_session_task` is only set by tasks that modify the dataframe (*data-extractopn* or *preprocessing*). So this will never be blocked by a compute tasks.

2024-09-23 14:54 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/model/task.py
> -            return ""
Yes I tested this. I found the root cause. By making this `status` property an expression it could be loaded without raising any errors.

2024-09-23 15:02 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/task_manager.py
> +            if source_database["type"] != "source":
I collected this in https://github.com/vantage6/vantage6/issues/1495

2024-09-23 15:06 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/model/column.py
> +    Each node has its own dataframe, which is a collection of columns.
Yes. Well, you can have several dataframes from one data source. But a dataframe can also be viewed as a 'global' dataframe. I stated that here to emphasize that if the user requests one dataframe it will get back the column names N times. (assuming that every node constructed the same dataframe).

I am not sure how to change the docstring to make that clearer.

2024-09-23 15:08 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/model/dataframe.py
> +        )
That would be less efficient? As then we retrieve all dataframes in the code and apply the filter in python?

2024-09-23 15:09 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/model/dataframe.py
> +            .filter(models.Task.status == TaskStatus.AWAITING.value)
The task is awaiting to be picked up. I kinda like it. As it is certainly not active at this point.

2024-09-23 15:10 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/model/dataframe.py
> +        # TODO FM 26-07-2024: The compute should be coming from an enum
Thanks. Noted it.

2024-09-23 15:13 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/collaboration.py
> +                      should be restricted to the same image
Yes and Yes that would make sense. I both added them to the sessions todo list.

2024-09-23 15:16 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/common/input_schema.py
> +            allowed_keys = {"label", "type"}
No, well we still have to decide. I think it is indeed a good idea to maintain this as we can use it to validate if a proper *data-extraction* method is provided. Or when we want to employ _smart_ *data-extraction* jobs that do the extraction based on the type (like we used to do).

I added this to the todo list.

2024-09-23 15:17 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/common/input_schema.py
> +    dtype = fields.String(required=True)
Yes but look where they are used. They have an agrument `many=True`.

2024-09-23 15:19 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/model/task.py
> +        return case([(cls.dataframe_id.is_(None), "compute")], else_="preprocess")
It is used so that we can use these methods to build pure sql alchemy queries. Making it much faster and we can make very complex selections in SQL.

2024-09-23 15:22 UTC, frankcorneliusmartin commented on vantage6/vantage6/cli/node/stop.py
> +        # ctx.docker_volume_name,
Removed, as this would remove all tracability of tasks. We need this for legal purposes. 

Besides that, sessions need to persistent between shutdown and start up. So these should definitely not be removed. (untill we have a better mechanism for storing data between start and stop)

2024-09-24 06:57 UTC, frankcorneliusmartin commented on vantage6-server/tests_server/test_resource_session.py
> +        conf = data["config"][0]
Yes in the overview issue I made an additional reminder that these should be implemented.

2024-09-24 07:01 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/common/output_schema.py
> +        setattr(self, "get_session", lambda obj: self.create_hateoas("session", obj))
I have tried to make it `session` for several hours. Somehow the method was not triggered when using the attribute `session`. I `session` might have been in use by the parent object or something like that. Ok to keep it like this?

2024-09-25 06:46 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/model/session.py
> +    def is_ready(cls):
You need both. You cant define the `.expression` without the property. And we need to `expression` else we would not be able to use the properties in queries.

2024-09-25 07:21 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/model/task.py
> +            )
Haha fair enough! I geus I got carried away with writing an epic SQLAlchemy expression. I refactored it.

2024-09-25 07:24 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/model/task_database.py
> +    that is used to identify a dataframe within a session.
I agree, I made a separate issue for this as this would change a lot of references.

2024-09-25 07:30 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/run.py
> +        #       Runs that are not finished and depending runs are not completed
There is no reason as of yet to split them in two? We could for clarity maybe in the UI? I made a separate issue for this.

2024-09-25 07:36 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/run.py
> +        # TODO FM 26-07-2024: We need to use a enum for the different states.
I think you ment `enum` and not `email` here. However I could not find that enum?

2024-09-25 07:44 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/run.py
> +        # TODO FM 26-07-2024: We need to use a enum for the different states.
I added the enum `TaskStatusQueryOptions` and replaced the values in several places.

2024-09-25 08:10 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/run.py
> +        )
I left is because I was not certain that the front-end was not using it. But it seems to me that the old socket event (also in v4.7) is unused, see: https://github.com/search?q=repo%3Avantage6%2Fvantage6%20status_update&type=code

So I am going to remove that event from here. But let me know if it is used in the front-end.

2024-09-25 08:16 UTC, frankcorneliusmartin commented on vantage6-algorithm-tools/vantage6/algorithm/tools/util.py
> +from vantage6.common.enum import LocalAction
I made a seperate issue for this.

2024-10-14 06:46 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/task_manager.py
> +        print(session_id)
Done

2024-10-14 07:13 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/task_manager.py
> +        if self.action == LocalAction.DATA_EXTRACTION:
Yes indeed, i factored the gaurds out. I also extracted the `proxy` part to make it even shorter.

2024-10-14 07:15 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/task_manager.py
> +            if not all(df["type"] == "handle" for df in databases_to_use):
I collect this one in a seperate issue.

2024-10-14 07:26 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/__init__.py
> +        # if container_action in [LocalAction.DATA_EXTRACTION, LocalAction.PREPROCESSING]:
Spend some time on remembering what I ment here. Couldnt so I removed it.

2024-10-14 14:43 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/socket.py
> +
No, it should be removed. This is how it worked in my first implementation. Now the `on_algorithm_status_change` socket event of the server sends `new_task` event to the nodes. This is much cleaner as it is not the shotgun method (avoiding a lot of requests).

I removed the code.

2024-10-14 14:51 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/model/column.py
> +if TYPE_CHECKING:
This way you can use actual references in you sql alchemy models without having the issue of circular imports, see: https://docs.python.org/3/library/typing.html#typing.TYPE_CHECKING

I removed the this and all other used imports.

2024-10-14 14:55 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/model/dataframe.py
> +    def ready(cls):
Look at the answer here: https://stackoverflow.com/questions/76467994/how-to-use-sqlalchemy-hybrid-method-and-hybrid-property I think it explains the relation very well.

I added a small doctring that hints in this direction.

2024-10-14 15:01 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +    add(scope=S.OWN, operation=P.VIEW, description="view your own session")
Fair, done.

2024-10-14 15:02 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +    def _can_session(self, session: db.Session, operation: P) -> bool:
I created a seperate issue for this.

2024-10-14 15:07 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +        session.delete()
Moved it to the DB model

2024-10-14 15:09 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +    "/session"
We never put class docstrings for resources. I added the endpoint here as a reminder. I can delete them?

2024-10-14 15:10 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +            ORGANIZATION, OWN
This was already there when I checked. But it could be that I added it in between.

2024-10-14 15:17 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/task.py
> +        # However they can also be user defined, although this has no use case yet.
I don't know what the use case would be either, but this can be usefull when defining heavy workloads. I dont see the harm in leaving it open?

2024-10-14 15:18 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/common/swagger_templates.py
> +                    "scope": "own",
This worked, and now it works for sure =]

2024-10-23 11:20 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/task.py
> +            databases = []
Lol, thanks :)

2024-10-24 09:43 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/task.py
> +        )
This indeed seems like a remnant of the past. I removed it.

2024-10-24 09:43 UTC, frankcorneliusmartin commented on vantage6-server/tests_server/test_resource_session.py
> +        node = Node.get_by_api_key("123e4567-e89b-12d3-a456-426614174000")
This magic value comes from the `unittest_fixtures.yaml`.

2024-10-24 09:46 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/common/output_schema.py
> +        # )
Yes!

2024-10-24 09:54 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/common/input_schema.py
> +                )
Refactored to a single function for `_validate_organizations`

2024-10-24 09:55 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/common/input_schema.py
> +    dtype = fields.String(required=True)
>  Do we want to validate which dtypes are possible
Since these are supplied by the node automatically I would not worry to much about the input.

2024-10-24 11:49 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +                                self.obtain_auth_collaboration_ids()
Yes!

2024-10-24 11:55 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +            return {"msg": "Collaboration not found"}, HTTPStatus.NOT_FOUND
Yes, good catch, thanks!

2024-10-24 11:58 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +    @only_for(("user",))
Sure. Although I think this is not bad either?

2024-10-24 11:59 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +                "msg": "This session has dependents, please delete them first."
Thanks!

2024-10-24 12:04 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +          required: true
Added the docs.

2024-10-24 12:07 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/common/swagger_templates.py
> +                    },
I made a separate issue in #1495 to rename handle to name for dataframes

2024-10-24 12:12 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +            while (handle := generate_name()) and db.Dataframe.select(session, handle):
I added the `s_` for sessions and `df_` for dataframes as prefixes to the generated names. It looks ugly, but it makes sense.

2024-10-24 12:24 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/task.py
> +            if not image.endswith(container["image"]):
I updated it in this branch

2024-10-24 12:30 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +            ),
Ok, when no description is given or an empty one this default will be used.

2024-10-24 12:33 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +            return response, status_code
Yes good catch!

2024-10-24 12:40 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +    def post(self, session_id, dataframe_handle):
I used POST as you this is essentially creating a new resource at the server. From a conceptual point of view we could also have made it a PATCH (although we are patching the dataframe at the nodes and not records at the server, so I dont think that will be RESTful).

We could rerout it, but that would look quite ugly in the code as we would create a seprate resource, so I rather not do it. Let me know if you insist.

2024-10-24 12:41 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +            description=f"Preprocessing step for session {session.name}",
Yes. Again there is a default when you do not provide one.

2024-10-24 12:56 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +    def post(self, session_id, dataframe_handle):
Ok at first I didnt like your suggestion, but indeed it looks nicer.

2024-10-24 12:57 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +        """Nodes report their column names
Same

2024-10-24 13:08 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/common/output_schema.py
> +        setattr(self, "get_session", lambda obj: self.create_hateoas("session", obj))
Ok this got me curious in the end. So after some digging. Our schema's parent objects from `marshmallow-sqlaclhemy` have reserved the word session, see:

https://github.com/marshmallow-code/marshmallow-sqlalchemy/blob/1330b08b41bf3c7e6b849cfff843f0942bdb7dce/src/marshmallow_sqlalchemy/load_instance_mixin.py#L23-L26

So I can finaly rest.

2024-10-28 12:43 UTC, bartvanb commented on vantage6-algorithm-tools/vantage6/algorithm/tools/decorators.py
> +def source_database(func) -> callable:
The new docstring is still not really clear to me but I added a new comment in the new location of this code

2024-10-28 12:47 UTC, bartvanb commented on docs/features/algorithms/sessions.rst
> +    Task "0" - "1" DataFrame
> Task - Dataframe. 0 - 1 is correct. This relationship is only set when a dataframe is modified

Could you add an explanation of that to the docs? If it's not clear to me, it's probably not clear to all other readers. (I still don't understand it now but I don't remember the figure and not a good moment to build it locally here right now)

2024-10-28 12:54 UTC, bartvanb commented on docs/features/algorithms/sessions.rst
> +        not dependant on (4) as in this case (7) was requested after (4) was completed.
Let's discuss it with an example. Say I've created a session with a number of filters. I then do a task (task A) to compute the average age. Later, I think of yet another filter that I have to apply to my dataframe (task B). 
A month later, I have forgotten which task I did first, task A or B. If I did B first, I don't have to repeat A as I would still get the same result. If I did A first, I'd have to rerun it because my results have probably changed.

Now what I wanted to say is that I think it should be immediately obvious whether A or B was done first, and/or whether tasks have been done on the latest version of the dataframe or not. I don't have the locally-built docs before me right now but I think this might be improved

2024-11-22 13:41 UTC, bartvanb requested changes
I went over it again and still had a quite a number of comments, even though I now also worked with it a bit from the Python client and liked the experience. Even though I know we want to merge this soon, I made an effort to be precise, but I think by far most comments are tiny and easily resolved, and/or can be converted to separate issues to resolve later. @frankcorneliusmartin let's discuss them in a meeting so we can act more quickly

Some generic comments that I had while testing:
1. I've done some testing but I think we should have Rian start on the UI part soon because that allows for more easy and therefore thorough testing
2. Before merging, I think the unittests/codacy/linting issues should be resolved
3. For default session/df names, can we get rid of the `s_` and `df_` prefixes? The user probably already knows what they are looking at so seems superfluous. If we do keep them, `s_` to `ses_` to avoid confusion about that abbreviation
4. There is already an issue to change dealing with dataframes by ID instead of 'handle' (and renaming handle to name) right?
5. In the docs there is somewhere: "You can inspect the log on the node by using the command ``parquet-tools show state.parquet``." -> maybe create command `v6 node inspect-session`?
6. There are some issues with `make devdocs` that I think are related to the SQLalchemy `hybrid_property` and `expression` (they have same function name) - but not sure. We should fix that
7. Idea: it would be cool if we have all the preprocessing functions stored somewhere in a module, so that people can easily import these into their own algorithm images (easier than redoing our algorithm images. This is also specifically useful for setting `session_restrict_to_same_image` as they wouldn't need to copy the code of community preprocessing functions into their own algorithm
	- Similar for data extraction functions: reading CSV, Excel etc should be simple importable functions I think.
	- This may be related to [[Feature Request] Simple Sessions · Issue #1477 · vantage6/vantage6](https://github.com/vantage6/vantage6/issues/1477)
8. I think this PR is not yet compatible with the algorithm store. Are there already issue(s) for that?
9. Is there an issue to ensure that docs are completed before release?
10. Unit tests are there for a bit of the (server) code, but limited. Is there an issue to ensure that tests are extended before release?

2024-11-22 13:41 UTC, bartvanb commented on vantage6-node/vantage6/node/docker/task_manager.py
> +        if self.action == LocalAction.DATA_EXTRACTION:
I meant more something like
```
if self.action == LocalAction.DATA_EXTRACTION:
    env_vars_db = self._get_env_vars_database_extract()
else:
    env_vars_db = self._get_env_vars_dataframe()
```

2024-11-26 13:25 UTC, bartvanb commented on docs/features/algorithms/sessions.rst
> +        not dependant on (4) as in this case (7) was requested after (4) was completed.
Discussed: we basically want a client-side function that shows which extraction+preprocessing steps have occurred for creating the DF of a compute task. And a flag that indicates if a task has been run on the latest version of the session's dataframe(s)

2024-11-26 13:29 UTC, bartvanb commented on vantage6-common/vantage6/common/enum.py
> +class LocalAction(EnumBase):
Discussed together: `AlgorithmStepType` will be the one.

2024-11-26 13:43 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/common/input_schema.py
> +    dtype = fields.String(required=True)
@frankcorneliusmartin convinced me in this case because it will be easier to run different versions of node and server

2024-11-26 14:12 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/session.py
> +        # can see the sessions in the collaboration that have a scope collaboration.
Implementation of `can_view_session` needs to be fixed, it's correct in the comment

2024-11-26 14:18 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/task.py
> +        # any running modification tasks (could also be none).
In summary: can you clarify that the `depends_on_ids` are submitted by another endpoint that is calling this function?

2024-11-26 14:23 UTC, bartvanb commented on vantage6-server/vantage6/server/websockets.py
> +                )
Conclusion: we should rename `new_task` because task is not new, but dependent has finished. There is a *chance* that node needs to pick up new algorithm run (which should be clarified in the comment)

2024-11-27 08:04 UTC, frankcorneliusmartin commented on vantage6-algorithm-tools/vantage6/algorithm/decorator/source_database.py
> +        in combination with the `data_extraction` decorator. This is Because this
*why* - the algorithm developer can use this function to supply a user requested database_uri to the function arguments. I think keeping the decorators is a good thing because:This is a decorator to obtain the URI, there might also bet other decorators to be used in combination with the `@data_extraction` decorator. 


I like keeping the decorator separate as if you open up an algorithm now, you can immediately see which action (`AlgorithmStepType`) the function is responsible for. So for me the purpose of the `@data_extraction`, `@preprocessing` and `@compute` is two fold: 1) annotate the function so it is clearer for the reader. 2) Validate that the node started the correct action. This second part is important as different `AlgorithmStepType` are supplied differently (different risk).

I added an example of this to clarify it. Let me know if you are having doubts.

2024-11-27 08:07 UTC, frankcorneliusmartin commented on vantage6-algorithm-tools/vantage6/algorithm/decorator/source_database.py
> +        in combination with the `data_extraction` decorator. This is Because this
I also changed the docstring a little bit so it is clearer that you can use the `source_database` without the `data_extraction` decorator as the later merely check that the node started the function as the correct `AlgorithmStepType`

2024-11-27 08:16 UTC, frankcorneliusmartin commented on vantage6-algorithm-tools/vantage6/algorithm/decorator/source_database.py
> +        uri = os.environ.get(ContainerEnvNames.DATABASE_URI.value, mock_uri)
This is a parallel from: 

https://github.com/vantage6/vantage6/blob/83ec80a881bfe03f78c43e45771e69f086a6cc8a/vantage6-algorithm-tools/vantage6/algorithm/tools/decorators.py#L157-L171

Also you do not use `@source_database(mock_uri)` as the `mock_uri` argument is part of the inner decorator. The `MockAlgorithmClient` is however not ready for this as it only supplied the `mock_data` argument: https://github.com/vantage6/vantage6/blob/83ec80a881bfe03f78c43e45771e69f086a6cc8a/vantage6-algorithm-tools/vantage6/algorithm/tools/mock_client.py#L246

I created a separate issue for this: #1600

2024-11-27 08:22 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/subclients/dataframe.py
> +    @post_filtering(iterable=False)
Two issues: 

- https://github.com/vantage6/vantage6/issues/1601
- https://github.com/vantage6/vantage6/issues/1602

2024-11-27 08:32 UTC, frankcorneliusmartin commented on docs/features/algorithms/sessions.rst
> +    Task "0" - "1" DataFrame
I added it to the explanation below. But the df keeps only track of the last task that modified the data frame. Of course you are able to reconstruct the entire modification chain by just checking which task that depends on (daisy chaining).

2024-12-02 14:05 UTC, frankcorneliusmartin commented on docs/features/algorithms/sessions.rst
> +        not dependant on (4) as in this case (7) was requested after (4) was completed.
Created a separate issue #1612

2024-12-02 14:06 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/rich/table.py
> +    table.add_column("Column Name", justify="left", no_wrap=True)
https://github.com/vantage6/vantage6/issues/1495 Added it here to not forget

2024-12-02 14:09 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/rich/table.py
> +    table.add_column("Dataframe")
Noted it here: https://github.com/vantage6/vantage6/issues/1495

2024-12-02 14:12 UTC, frankcorneliusmartin commented on vantage6-server/tests_server/test_resource_session.py
> +        node = Node.get_by_api_key("123e4567-e89b-12d3-a456-426614174000")
I added in the comment above.

2024-12-02 14:24 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/model/session.py
> +    from vantage6.server.model.collaboration import Collaboration
Remnant of an early implementation. Thanks. Cleaned uit up.

2024-12-02 14:27 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/model/session.py
> +    from vantage6.server.model.collaboration import Collaboration
This is to avoid circular imports in models. The `TYPE_CHECKING` will be set to True when the IDE is checking the imports. This makes this class available in this class so we can get proper typehints. See https://docs.sqlalchemy.org/en/20/orm/extensions/mypy.html#mapping-relationships

2024-12-02 14:29 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/model/session.py
> +        )
Check

2024-12-02 14:32 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/model/task.py
> +            return "no action as there are no runs"
You are right. I removed the validation part.

2024-12-02 14:49 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/model/task.py
> +    def status(cls):
And also in the `.filter(` methods!

2024-12-02 14:49 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/__init__.py
> +    def is_node() -> bool:
OK

2024-12-02 14:52 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/common/input_schema.py
> +    session_restrict_to_same_image = fields.Boolean(required=True)
Agreed.

2024-12-02 14:55 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/common/output_schema.py
>      def databases_(obj):
Yes please

2024-12-02 15:02 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/run.py
> +        # we should mark the dependent tasks as failed as well.
Logged in the overview issue for the prerequisite: https://github.com/vantage6/vantage6/issues/1495

I agree with your other comment. However this still can lead to unexpected results if the compute step depends on the preprocessing to be done. It a matter of choice, for now I implemented as you suggested.

2024-12-02 15:05 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +        """Helper for determining permissions for deleting and editing a session"""
In this case its a private helper function. I don't feel like extending as it would be a repetition of the `can_delete_session` and `can_edit_session`

2024-12-02 15:09 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +        """Create a task to initialize a session"""
Done

2024-12-02 15:10 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +            input_, self.socketio, getattr(self.permissions, "task"), {}, action
`self.config` is available in the `ServiceResources`, also I removed the print :)

2024-12-02 15:29 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +          collaboration or organization.
This is a difficult concept. I clarified the docstrings and we should indeed cover this good in the docs.

2024-12-02 15:31 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +    "/session/<int:session_id>/dataframe"
I logged this into: https://github.com/vantage6/vantage6/issues/1495 as permissions and endpoints would change. So in that case we would have to rethink the general app structure as I dont think we should change the endpoints because of an internal refactor.

2024-12-02 15:34 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +    @with_user
Done

2024-12-02 15:40 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +            dataframe=dataframe,
Fixed this, there are now settable from the data_extraction and preprocessing endpoint.

2024-12-02 15:42 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +        )
Ok. fair.

2024-12-02 15:44 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +    "/session/<int:session_id>/dataframe/<string:dataframe_handle>"
It logged here: https://github.com/vantage6/vantage6/issues/1495

2024-12-02 15:48 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +            }, HTTPStatus.BAD_REQUEST
Ok also removed from the client.

2024-12-02 15:48 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +        )
Done

2024-12-02 15:49 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +    "/session/<int:session_id>/dataframe/<string:dataframe_handle>/column"
Logged this into https://github.com/vantage6/vantage6/issues/1495 and as previously we should then consider a new kinda structure as putting these in different files would change the endpoints, which I dont want to do :)

2024-12-02 15:50 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/task.py
> +            databases = []
Yes.. forgot to commit it.

2024-12-02 15:53 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/task.py
> +        # any running modification tasks (could also be none).
That comment was already there?

> These `depends_on_ids` are the task ids supplied by the session endpoints.

2024-12-02 15:55 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/task.py
>              store = parent.algorithm_store
Sure. Done.

2024-12-02 15:56 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/task.py
> +            db_records.append(task_db)
You are right. Good catch!

2024-12-02 15:58 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/websockets.py
> +                )
I stayed close to the original. I named it `new_task_update`.

2024-12-02 15:59 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/__init__.py
> +            dataframe: int = None,
Done

2024-12-02 15:59 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/subclients/dataframe.py
> +            rich_dataframe_table(dfs["data"])
Yes, here: https://github.com/vantage6/vantage6/issues/1481

2024-12-02 16:02 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/subclients/dataframe.py
> +        session = self.parent.request(f"session/{session_id}")
There is already handling in the `parent.request` methods? Or do you want to stop executing if an error happens there?

2024-12-02 16:05 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/subclients/dataframe.py
> +        session = self.parent.request(f"session/{session_id}")
We hardly do this anywhere in the client code? I did add a simple check that the request method returned something (so a non 200 code).

2024-12-02 16:06 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/subclients/dataframe.py
> +        session = self.parent.request(f"session/{session_id}")
I logged it into, to have another look at it later.. https://github.com/vantage6/vantage6/issues/1495

2024-12-02 16:10 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/subclients/session.py
> +                "per_page": per_page,
We do it like this in all old endpoints? I see that in the algorithm store you actually checked for nones. I suggest we appy the same logic to all other client function. I logged it in:; https://github.com/vantage6/vantage6/issues/1495

2024-12-02 16:13 UTC, frankcorneliusmartin commented on vantage6-common/vantage6/common/enum.py
> +        ]
Yes... you are right.

2024-12-02 16:15 UTC, frankcorneliusmartin commented on vantage6-algorithm-tools/vantage6/algorithm/decorator/action.py
> +        return result
How would you check that? For now I added a mental note, so we can disucuss this later as I agree it would be better to force it. But I dont see how now.

2024-12-02 16:19 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/__init__.py
> +                    "finished_at": datetime.datetime.now().isoformat(),
Smart.

2024-12-02 16:24 UTC, frankcorneliusmartin commented on vantage6-algorithm-tools/vantage6/algorithm/tools/exceptions.py
> +      the correction action (data extraction, preprocessing, etc.)
I agree. I logged it into https://github.com/vantage6/vantage6/issues/1495

2024-12-02 16:27 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/docker_manager.py
> +        while not (task.status == RunStatus.ACTIVE) and attempts < 3:
Sure, although this was not really part of this PR :P

2024-12-02 16:28 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/docker_manager.py
> +        while not (task.status == RunStatus.ACTIVE) and attempts < 3:
I also made the sleep into a constant

2024-12-02 16:29 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/task_manager.py
> +        self.session_state_file_name = "state.parquet"
I logged this into https://github.com/vantage6/vantage6/issues/1495

2024-12-02 16:31 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/task_manager.py
> +                    "file": filename,
Sure.

2024-12-02 16:31 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/task_manager.py
> +        self.session_folder = "/mnt/session"
Removed it.

2024-12-02 16:36 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/task_manager.py
> +            raise DataFrameNotFound(f"user requested {requested_handles}")
Yes good suggestion.

2024-12-02 16:40 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/subclients/dataframe.py
> +        org = self.parent.organization.list(**params)
Logged into https://github.com/vantage6/vantage6/issues/1495

2024-12-02 16:42 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +        session.delete()
Haha LOL yes.

2024-12-02 16:42 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +    "/session"
Removed it.

2024-12-03 11:07 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/session.py
> +        # can see the sessions in the collaboration that have a scope collaboration.
After a short call, it seemed like the implementation was correct after all.

2024-12-11 15:29 UTC, merged

2025-07-17 12:43 UTC, bartvanb commented on vantage6-algorithm-tools/vantage6/algorithm/decorator/action.py
> +        return result
I added a check to achieve this in https://github.com/vantage6/vantage6/pull/2143