Feature/set allowed algorithms from store
vantage6/vantage6 pull request #1318
Opened 2024-06-12 12:31 UTC by bartvanb

Fix #1293, #1198

- node can define policies to allow any algorithm from a whitelisted algorithm store
- algorithm store saves algorithm image digest when it is posted to the store using manifest from OCI v2 API
- task have new field `store_id` to save which store algorithm was taken from (optional - you can still run algorithms outside the store)
- when task is created from a certain algorithm store, it verifies with the store that the algorithm is in there. Also, the digest is stored as part of the image even if the user did not specify it - this way it can be checked later with which algorithm image version the algorithm was run
- **code to check `allowed_algorithms` has been updated**
- UI, python client and algorithm client have been updated where necessary

2024-06-12 13:57 UTC, bartvanb commented
We can ignore the codacy issue

2024-06-12 15:14 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/task.py
> -        )
note that this socket event was not listened to anywhere

2024-06-19 12:52 UTC, wbaccinelli approved these changes
Looks good! I don't have any useful input for the PR 😅

2024-06-19 12:52 UTC, wbaccinelli commented on vantage6-server/vantage6/server/algo_store_communication.py
> +    print("params in request_algo_store", params)
was this for debugging?

2024-06-19 12:52 UTC, wbaccinelli commented on vantage6-server/vantage6/server/model/task.py
> +        List of databases that are part of this task
should also `alsgorithm_store` be added to the attributes?

2024-06-19 14:58 UTC, bartvanb commented on vantage6-server/vantage6/server/algo_store_communication.py
> +    print("params in request_algo_store", params)
thanks for spotting that

2024-06-19 15:01 UTC, bartvanb commented on vantage6-server/vantage6/server/model/task.py
> +        List of databases that are part of this task
Indeed! And there were actually also a couple of others missing so added those as well

2024-06-19 15:01 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/__init__.py
> +def with_permission_to_view_algorithms() -> callable:
Done

2024-07-04 12:43 UTC, frankcorneliusmartin commented on vantage6/vantage6/cli/configuration_wizard.py
> +    )
... match multiple **algorithm stores** ...
and
... one algorithm **store** at the time.

2024-07-04 12:49 UTC, frankcorneliusmartin commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/algorithm.py
> +            Configuration dict
`config` is not an parameter

2024-07-04 13:03 UTC, frankcorneliusmartin commented on vantage6-common/vantage6/common/docker/addons.py
> +        )
I am a little worried about this as the basic auth is not specified by OCI. I found this source that tells me that bearer is also used by Github Container Registry and Azure Containers:

https://github.com/richlander/container-registry-api?tab=readme-ov-file#authorization

Which registries did you check?

2024-07-04 13:09 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/docker_manager.py
> +                        algorithm_whitelisted = True
And how about specific tags from an image?

2024-07-04 13:16 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/model/task.py
> +        Algorithm store that this task belongs to
I would rather say 
 
```suggestion
        Algorithm store that this task uses
```

2024-07-04 13:28 UTC, frankcorneliusmartin commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/algorithm.py
> +        return image_wo_tag, response.headers["Docker-Content-Digest"]
What are the consequences if this header is not present? This is an optional header as specified here: https://github.com/opencontainers/distribution-spec/blob/v1.1.0/spec.md#legacy-docker-support-http-headers

2024-07-04 13:33 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/task.py
> +        return self.post_task(request.get_json(), self.socketio, self.r, self.config)
This endpoint will return a 500 now when someone posts without a JSON body. (I am aware that this was probably me, and this already existed)

2024-07-04 13:38 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/task.py
> +                }, HTTPStatus.BAD_REQUEST
I don't think `BAD_REQUEST` is the best code? I think FORBIDDEN would be more appropiate?

2024-07-04 13:44 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/task.py
> -        )
I am a little surpised. But indeed :') There is another socket event `new_task`..

2024-07-04 13:45 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/task.py
> +        if image and not digest:
Will it ever get here? Is `algorithm["digist"]` always present? And in case it does not have a digist it returns `""`?

2024-07-04 13:50 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/task.py
> +            server_url=get_server_url(config, request.args.get("server_url")),
It seems to me that and `config.get("server_url", request.args.get("server_url"))` can return `None` in `get_server_url`? I think both are not garanteed as one is dependent on the user and the other on the node administrator?

Maybe check that one of them is present and in case not, thow an error code back.

2024-07-04 13:53 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/task.py
> +            raise Exception("Algorithm not found in store!") from e
Maybe add an additional `except` to catch all? `.json()` can raise `requests.exceptions.JSONDecodeError`

2024-07-04 13:57 UTC, frankcorneliusmartin requested changes
Some concerns regarding the standardization of OCI and some other minor changes/suggestions.

Looks good.

2024-07-05 07:30 UTC, bartvanb commented on vantage6/vantage6/cli/configuration_wizard.py
> +    )
Good spot, important fix!

2024-07-05 07:31 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/algorithm.py
> +            Configuration dict
deleted it

2024-07-05 07:47 UTC, bartvanb commented on vantage6-node/vantage6/node/docker/docker_manager.py
> +                        algorithm_whitelisted = True
I added this TODO:
        # TODO also allow for "some/image:tag"? In that case, be sure to
        # prevent that if the allowed algorithm expression is "some_image",
        # that "some_image:443.com/whatever" is NOT allowed, i.e. the check
        # 'docker_image_name.startswith(f"{algorithm}:")' is not enough

Since it's not trivial and also wasn't possible up to now and no-one asked for it, I suggest to leave it. Note btw that the extra sha check *IS* necessary because the server will now add the sha256 to the requested algorithm image in the task if the algorithm store provides it to the server.

2024-07-05 07:52 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/task.py
> +        return self.post_task(request.get_json(), self.socketio, self.r, self.config)
I think it was probably me because I created the `post_task` function so that I could call it from the GET `/ui/column` endpoint I think. But anyway, to fix it I put a try/except around the get_json()

2024-07-05 07:57 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/task.py
> +                }, HTTPStatus.BAD_REQUEST
I have no strong preference so I changed to FORBIDDEN as you suggested

2024-07-05 08:05 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/task.py
> +            server_url=get_server_url(config, request.args.get("server_url")),
You're right, in the current implementation I expect it would fail making the request to a `None` endpoint, however now I added an exception to make the user get a clear error

2024-07-05 08:08 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/task.py
> +        if image and not digest:
Algorithm digest will always be present in the store when this PR is merged, however, in current versions (4.3-4.5) it is not. So to keep stores that are updated to 4.6+ backwards compatible, this check is here. 
I'll add a TODO to remove this in 5.0

2024-07-05 08:10 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/task.py
> +            raise Exception("Algorithm not found in store!") from e
I just changed the current `KeyError, IndexError` to generic `Exception` as that is most fail-proof

2024-07-05 11:39 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/algorithm.py
> +        return image_wo_tag, response.headers["Docker-Content-Digest"]
Very good question. The consequence would have been that the digest was not determined and therefore algorithm could not be submitted.
I have therefore now created an alternative method `__calculate_digest` which calculates the digest from the manifest.

2024-07-08 00:33 UTC, lsago reviewed
I've only reviewed this partially, as I'm not familiar with new algo store code base.

2024-07-08 00:33 UTC, lsago commented on docs/algorithm_store/yaml/algorithm_store_config.yaml
> +# to e.g. find the hashes of the algorithm.
As per below, if docker registry is public for an image (i.e. anybody can pull it), they should also be able to pull the manifest of that image and get the digest of it.

2024-07-09 06:19 UTC, bartvanb commented on docs/algorithm_store/yaml/algorithm_store_config.yaml
> +# to e.g. find the hashes of the algorithm.
I don't understand what the issue is here. I guess I'm missing what you mean by 'as per below', can you clarify?

2024-07-09 06:21 UTC, bartvanb commented on docs/node/node_config.yaml
> +    - ^https://*.vantage6.ai
Oops.. I now added two backslashes before the dots and a $ at the end.

2024-07-09 06:23 UTC, bartvanb commented on vantage6/vantage6/cli/configuration_wizard.py
> +        "^https://*.vantage6.ai$               Allow all algorithms from any "
here the $ was already there but the two \ have been added

2024-07-09 06:24 UTC, bartvanb commented on vantage6-common/tests/vantage6/common/docker/test_addons.py
> +# These tests are adapted from [1]. We do this because parse_image_name use
Changed

2024-07-09 06:28 UTC, bartvanb commented on vantage6-common/vantage6/common/docker/addons.py
> +        The full image url
Alright it may be clearer to remove this arg indeed so I'll do that, and improve the specification of the other ars

2024-07-09 06:39 UTC, bartvanb commented on vantage6-node/vantage6/node/docker/docker_manager.py
> +                if not self._is_regex_pattern(algorithm):
I think it's an excellent idea to separate them explicitly, as I totally agree that the current way is a bit funky. Can you create an issue for that? Otherwise let me know and I will do it.

For the time being we have to make sure that v4 nodes with regexes in `allowed_algorithms` will still be supported but we could already introduces the `allowed_algorithm_regexes` and then in v5 remove support for regex in `allowed_algorithms`. Or alternatively, we could implement this in v5 directly (should be there early 2025 so not too far away)

2024-07-09 07:10 UTC, bartvanb commented on vantage6-node/vantage6/node/docker/docker_manager.py
> +                        algorithm_whitelisted = True
I realize I was cutting corners I shouldnt cut when adding the TODO. People may already be having tag-based image filters so we should make sure they will keep working. I'll have a look at how to best implement this.

2024-07-09 12:11 UTC, bartvanb commented on vantage6-common/vantage6/common/docker/addons.py
> +        )
I just implemented the workflow of Luis, with a slight adaptation. To make it work on Dockerhub images, I also added the `service` parameter of the `www-authenticate` header, otherwise I still got a 401 there.

Tested this with Luis' image and also with `jhogenboom/average`, an algorithm image that Joshi made available via Dockerhub.

Note that the function does not support username/password-protected images yet - I left a TODO for that in the code, but didnt tackle it now as we don't have a use case at present.

2024-07-09 13:24 UTC, bartvanb commented on vantage6-node/vantage6/node/docker/docker_manager.py
> +                        algorithm_whitelisted = True
I now redid this implementation to allow images in the following cases:
- exact match (as available before)
- allowed algorithm is `some_image` and evaluated image is `some_image:tag` or `some_image@sha256...`
- if allowed algorithm is `some_image:tag_or_sha`  and evaluated image is `some_image:other_tag_or_sha`, the digest of both is computed and image is allowed if they are the same.

I personally think it's much nicer now but hope you can check it thoroughly as this is important to get right!

2024-07-09 21:51 UTC, lsago commented on docs/node/node_config.yaml
> +    - ^https://*\.vantage6\.ai$
Heh these regexes are error prone I think

```suggestion
    - ^https://.*\.vantage6\.ai$
```

Or maybe even more precise:
```suggestion
    - ^https://[a-z]+\.vantage6\.ai$
```

2024-07-10 00:11 UTC, lsago commented on vantage6-node/vantage6/node/docker/docker_manager.py
> +                        algorithm_whitelisted = True
Nice, I agree, this, at first glace, seems sensible to me as well. However I still want to have a thorough look at this, as I agree this is an important function to get right.

But, I'm submitting this review now so as not to delay switching to using `inspect_distribution()` *in case you consider it worth it*.   .. given we're hoping to ship this sooner rather than later as you said.

2024-07-10 00:11 UTC, lsago commented on vantage6/vantage6/cli/configuration_wizard.py
> +        "^https://*\.vantage6\.ai$               Allow all algorithms from any "
I guess here we are also missing a dot or something (e.g. `[a-z]`) before the Kleene star..


Or, something like..
```suggestion
        "^https://[a-z]+\.vantage6\.ai$               Allow all algorithms from any "
```

2024-07-10 00:11 UTC, lsago commented on vantage6/vantage6/cli/configuration_wizard.py
> +        "^harbor2\.vantage6\.ai/demo/average:@sha256:82becede...$    Allow a "
That `:` between `average` and `@sha256` turns it into an invalid reference I think. Probably just a typo :p

2024-07-10 06:48 UTC, bartvanb commented on docs/node/node_config.yaml
> +    - ^https://*\.vantage6\.ai$
Good catch, I really suck at regex :-) I've added the last version.

2024-07-10 06:50 UTC, bartvanb commented on docs/algorithm_store/yaml/algorithm_store_config.yaml
> +# to e.g. find the hashes of the algorithm.
Ah gotcha. I removed the section now as it's not implemented

2024-07-10 07:28 UTC, bartvanb commented on vantage6-common/vantage6/common/docker/addons.py
> +    return registry, repository, tag
I've adapted the function to remove the '4.5' tag in such cases and return the sha256. I've also updated the docstring and added the unittest. 

Obviously we have to choose what to return, tag or sha256 (or both). I now made the choice to return sha but if anyone feels strongly about it we can of course change that.

2024-07-10 07:33 UTC, frankcorneliusmartin requested changes

2024-07-10 07:33 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/docker_manager.py
> +                        algorithm_whitelisted = True
We should also break out of the loop? We've found what we are looking for? No need to scan for additional matching patterns? (Same goes for all other `True`s)

2024-07-10 07:33 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/docker_manager.py
> +                    evaluated_img_wo_tag, _ = parse_repository_tag(evaluated_img)
You probably should do this outside of the for-loop.

2024-07-10 07:33 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/docker_manager.py
> +                            )
If either one of the exceptions is reached you should explicitly leave this block. As the verification bellow may be compromised. I dont think relying on `None` to be outputed from an exception block is safe.

2024-07-10 07:33 UTC, frankcorneliusmartin commented on vantage6-common/vantage6/common/docker/addons.py
> +from http import HTTPStatus
This from import should move lower to the `from` imports block. Isnt that Black?

2024-07-10 07:34 UTC, frankcorneliusmartin requested changes
Some final remarks

2024-07-10 09:18 UTC, bartvanb commented on vantage6-common/vantage6/common/docker/addons.py
> +from http import HTTPStatus
There's a pylint rule that imports from the standard library have to come before imports from other dependencies. So in order to not violate that I'll leave this here.

2024-07-10 09:45 UTC, bartvanb commented on vantage6/vantage6/cli/configuration_wizard.py
> +        "^harbor2\.vantage6\.ai/demo/average:@sha256:82becede...$    Allow a "
I guess you're right, well spotted

2024-07-10 09:47 UTC, bartvanb commented on vantage6-node/vantage6/node/docker/docker_manager.py
> +                        algorithm_whitelisted = True
You're right, not expecting a major performance boost but who knows how node configurations may look in the future

2024-07-10 09:49 UTC, bartvanb commented on vantage6-node/vantage6/node/docker/docker_manager.py
> +                            )
`get_digest()` has now been modified to return `None` if digest is not returned. Is this OK now?

2024-07-10 09:55 UTC, bartvanb commented on vantage6-node/vantage6/node/docker/docker_manager.py
> +                if not self._is_regex_pattern(algorithm):
I created this issue just now.

2024-07-10 10:14 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/docker_manager.py
> +                        algorithm_whitelisted = True
I like it. Not because of performance but for clarity

2024-07-11 08:50 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/docker_manager.py
> +                            )
Yes thats clearer

2024-07-11 08:51 UTC, frankcorneliusmartin approved these changes

2024-07-11 11:09 UTC, merged

2024-07-21 22:42 UTC, lsago reviewed
I like the idea of comparing digest (allowed) to digest (requested) in the images, seems like the most solid approach.

I leave something to probably consider before release.

2024-07-22 08:36 UTC, bartvanb commented on vantage6-node/vantage6/node/docker/docker_manager.py
> +                        algorithm_whitelisted = True
So *I think* we could resolve this by having `parse_repository_tag` return the actual tag rather than the sha256 as 'tag'. A tag is always pointed to 1 image hash, so that wouldn't be an issue. Then `parse_repository_tag` should do the following

```
parse_repository_tag("somename:sometag@sha256:somehash") == ("somename", "sometag")
```

If it does, that would work with the following policies:

- allowed image `somename:sometag`: tags are the same so same image
- allowed image `somename@sha256:somehash`: the hash for `sometag` would be retrieved and if that is the same as `somehash` it will be allowed
- allowed image `somename:sometag@sha256:somehash`: in this case, hash would also be retrieved and compared

So the choice I made previously to return the hash rather than the tag seems to be unfortunate - by returning the tag rather than the hash we could resolve these issues I think

2024-07-22 08:59 UTC, bartvanb commented on vantage6-node/vantage6/node/docker/docker_manager.py
> +            evaluated_img_wo_tag, _ = parse_repository_tag(evaluated_img)
Good spot, I'll replace the use of the library function here with the improved function from the addons