Add some extra clarifications on docs concerning linked docker services
vantage6/vantage6 pull request #1329
Opened 2024-06-14 07:22 UTC by bartvanb

2024-06-16 20:22 UTC, frankcorneliusmartin requested changes

2024-06-16 20:22 UTC, frankcorneliusmartin commented on docs/features/node/linked_docker_service.rst
> +.. code:: python
This code example is specifix for http. Maybe good to mention that this also works for other protocols.

2024-06-16 20:22 UTC, frankcorneliusmartin commented on docs/features/node/linked_docker_service.rst
>  running, so your algorithm will be able to access it via `http://localhost`.
Then this is also not a true statement, right?

2024-06-19 06:59 UTC, bartvanb commented on docs/features/node/linked_docker_service.rst
>  running, so your algorithm will be able to access it via `http://localhost`.
True, removed it

2024-06-19 07:00 UTC, bartvanb commented on docs/features/node/linked_docker_service.rst
> +.. code:: python
done

2024-06-20 07:05 UTC, CunliangGeng commented
Did you update Ubuntu version for https://docs.vantage6.ai/en/main/node/requirements.html?

2024-06-20 07:56 UTC, bartvanb commented
> Did you update Ubuntu version for https://docs.vantage6.ai/en/main/node/requirements.html?

Yes, see [0b4cba1](https://github.com/vantage6/vantage6/pull/1329/commits/0b4cba10c7231e6e534cfc0f0d965dfc3294baf0) :-)

2024-07-04 09:49 UTC, merged