Feature/algo store review
vantage6/vantage6 pull request #1358
Opened 2024-07-01 14:04 UTC by bartvanb

Fix #981 

Note that this PR also includes commits that should be merged in #1318 so better to review/merge that one first.

2024-07-04 15:14 UTC, wbaccinelli approved these changes
This is a lot of work, great job! 
I wonder whether having multiple independent `reviews` attached to an algorithm makes the process of a review a bit less clear. Maybe having a global review container that aggregates all the single reviews could make the concept of review process a bit more easy to manage. But I don't know what level of complexity it would add. Anyway, it works! 
I have some minor comments.

2024-07-11 11:19 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/model/algorithm.py
> +    documentation_url = Column(String)
added

2024-07-11 11:53 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/__init__.py
> +                or request_args.get("invalidated")
Thanks a lot for this question! It inspired me to create #1379. I'm not going to change this here as this is something we are not doing anywhere but should do everywhere - better to do it all systematically.

2024-07-11 11:57 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/review.py
> +    add(P.DELETE, description="Delete reviews")
Yes, this is currently a rule with operation 'review' on resource 'algorithm', but it makes indeed more sense to create 'review edit' for that. I'll change it

2024-07-11 13:06 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/review.py
> +                    continue
The current implementation is indeed not desirable. However, I believe we should not always invalidate algorithms of the same image under review, e.g. if we have two versions simultaneously under review:

Suppose I have three versions of an algorithm: A, B and C. First A was submitted, then B, then C. If A is approved and both B and C are under review, if B is approved, I do not yet want to invalidate C.

So I added a condition to check on submission date and not invalidate a newer version that is under review

2024-07-11 13:12 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/algorithm.py
> +        if algorithm.approved_at is not None:
The algorithms where `approved_at is None` are either awaiting review assignment or under review. I see your point but prefer to use this as it's a single condition instead of two

2024-07-11 13:13 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/algorithm.py
> +        elif algorithm.invalidated_at is not None:
Same as above: because I'd also have to check AlgorithmStatus.REPLACED and potentially other statuses we add in the future. Checking 1 property is easier

2024-07-11 13:16 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/review.py
> +                algorithm.status = AlgorithmStatus.APPROVED
Yes that is correct. With the current implementation we always require >1 review, so 1 review is still enough. I am planning to implement policies so that this is configurable (#1365), then we also need to change this code again

2024-07-11 13:18 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/review.py
> +                algorithm.status = AlgorithmStatus.AWAITING_REVIEWER_ASSIGNMENT
If we get here, the current review was the *only* review, so there are 0 others. So then new ones need to be assigned.

2024-07-11 13:22 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/review.py
> +class ReviewApprove(AlgorithmStoreResources):
Good catch! I added a check to the `approve` and `reject` endpoints that reviews can only be approved/rejected if their status is 'under review'

2024-07-11 13:28 UTC, bartvanb commented
> I wonder whether having multiple independent reviews attached to an algorithm makes the process of a review a bit less clear. Maybe having a global review container that aggregates all the single reviews could make the concept of review process a bit more easy to manage. But I don't know what level of complexity it would add. Anyway, it works!

I didn't really consider that in depth. I believe that the most common use case will be to have a single reviewer, so then this implementation would add one less layer of complexity. Also, as already mentioned in one of the comments, there is the plan to add policies for reviews (#1365) which will probably add some centralized functionality to check review/algorithm statuses.

2024-07-15 14:41 UTC, frankcorneliusmartin requested changes
Shouldnt there be a way to resubmit a invalidated (rejected) algorithm?

2024-07-15 14:41 UTC, frankcorneliusmartin commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/algorithm.py
>                  setattr(algorithm, field, data.get(field))
at line 768 `image = data.get("image")` should be `image = data["image"]`

2024-07-15 14:41 UTC, frankcorneliusmartin commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/review.py
> +import datetime
imports go first

2024-07-15 14:41 UTC, frankcorneliusmartin commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/review.py
> +        errors = review_update_schema.validate(request.get_json())
why not use `data` here?

2024-07-15 14:41 UTC, frankcorneliusmartin commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/review.py
> +                elif other_version.id == algorithm.id:
I prefer to have another OR in this case

2024-07-15 14:41 UTC, frankcorneliusmartin commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/user.py
> +import sqlalchemy
imports at the top

2024-07-15 14:41 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/subclients/store/review.py
> +        Create a review.
This desciption is to short. This should say something in the line of "request a review". Now it can be red as creating a review, which it does not do.

2024-07-16 06:31 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/model/algorithm.py
> +        Check if an algorithm is being reviewed.
Added

2024-07-16 06:34 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/model/review.py
> +        return self.status != ReviewStatus.UNDER_REVIEW
Haha I did this for exactly the same reason: if we add more statuses, I thought it was more likely that they are statuses where the review has been finished. But anyway, we just need to take care when adding new statuses

2024-07-16 06:43 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/model/user.py
> +    algorithms = relationship("Algorithm", back_populates="developer")
Do you feel strongly about this? Because we use the term `developer` in quite a few places already (there's a default role, a data field, UI code etc.). We could of course change it everywhere, but I think the name is appropriate.
To discuss the future situation, when would we use developer for something else? I would think that would be the case when we assign multiple developers to a single algorithm. This requires some changes to the data model that I don't think would be easy to make backwards compatible. Unless we have a main developer (which is the current one) and add others as co-developer. But then I think we could also use co-developer (or something else)

2024-07-16 06:44 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/schema/input_schema.py
> +    code_url = fields.String(required=True)
Yes. Uploading zips is not supported yet in this version, so for now the code_url is required, but in a next version, it should be either a code_url or a code zip.

2024-07-16 06:46 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/algorithm.py
>                  setattr(algorithm, field, data.get(field))
I don't think that's true, as this is the PATCH endpoint so the image is not necessarily updated.

2024-07-16 06:48 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/review.py
> +import datetime
I'm fine with changing this but this isnt a PEP rule I think (nor do we do this consistenly everywhere).

2024-07-16 06:48 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/review.py
> +        errors = review_update_schema.validate(request.get_json())
changed :-)

2024-07-16 06:50 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/review.py
> +                elif other_version.id == algorithm.id:
done

2024-07-16 06:53 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/user.py
> +import sqlalchemy
If I do that I get:
> standard import "from http import HTTPStatus" should be placed before "import sqlalchemy"Pylint[C0411:wrong-import-order](https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/wrong-import-order.html)

So I would propose following Pylint and put standard library imports on top (even if they are 'from x import y'). I did move this import above the flask imports as that is fine.

2024-07-16 06:54 UTC, bartvanb commented on vantage6-client/vantage6/client/subclients/store/review.py
> +        Create a review.
Updated

2024-07-16 06:59 UTC, bartvanb commented
> Shouldnt there be a way to resubmit a invalidated (rejected) algorithm?

I've created https://github.com/vantage6/vantage6/issues/1380 to address that

2024-07-16 07:19 UTC, frankcorneliusmartin commented on vantage6-algorithm-store/vantage6/algorithm/store/model/review.py
> +        return self.status != ReviewStatus.UNDER_REVIEW
Up to you

2024-07-16 07:23 UTC, frankcorneliusmartin commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/review.py
> +import datetime
You are right, this is not PEP. So I wont press to hard. But I like to order stuff as:

```python
import a_standard
import b_standard

import a_third_party
import b_third_party

from a_soc import f
from a_soc import g
from b_soc import d
```

2024-07-16 07:29 UTC, frankcorneliusmartin commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/algorithm.py
>                  setattr(algorithm, field, data.get(field))
Ah I see, I missed the `partial=True` in the schema validation. So I thought it was always present:
https://github.com/vantage6/vantage6/blob/9f337e08d2ad4ef96a427c6ed984e77420a2db41/vantage6-algorithm-store/vantage6/algorithm/store/resource/schema/input_schema.py#L36

2024-07-16 07:33 UTC, frankcorneliusmartin commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/user.py
> +import sqlalchemy
Yes so this is what I mention in the other comment.

2024-07-16 09:22 UTC, merged