Added base code of conduct
vantage6/vantage6 pull request #1480
Opened 2024-09-16 09:48 UTC by frankcorneliusmartin

2024-09-17 14:03 UTC, bartvanb commented on CODE_OF_CONDUCT.md
> +[INSERT CONTACT METHOD].
well what should we put here? Point them to discord and define there who the admins are?

2024-09-17 14:11 UTC, bartvanb requested changes

2024-09-17 14:11 UTC, bartvanb commented on README.md
> +The **vantage6** infrastructure is delivered in Docker images. To run these images, you need to have [Docker (docs.docker.com)](https://docs.docker.com/get-docker/) installed. To install the latest v
I guess you added these domain names to the link to make them more trustworthy but personally I don't like this as it disrupts the reading flow and also there are no guarantees that you actually link to those domains so it's a false sense of security. 
All in all for me, the added value would only outweigh the cons if we expect a lot of people want to click these links, which at least for the ones above I don't think will happen

2024-09-17 14:11 UTC, bartvanb commented on README.md
> +The **vantage6** infrastructure is delivered in Docker images. To run these images, you need to have [Docker (docs.docker.com)](https://docs.docker.com/get-docker/) installed. To install the latest v
Also line length is too long, best to spread over a few lines.

2024-09-23 08:50 UTC, frankcorneliusmartin commented on README.md
> +The **vantage6** infrastructure is delivered in Docker images. To run these images, you need to have [Docker (docs.docker.com)](https://docs.docker.com/get-docker/) installed. To install the latest v
I added them to make clear they are brought to an external website. Not for trust, never trust link names...

2024-10-15 07:49 UTC, dsmits approved these changes
LGTM

2024-10-22 12:45 UTC, CunliangGeng approved these changes
LGTM too. Nice to add the code of conduct!

2024-10-25 14:30 UTC, bartvanb commented on README.md
> +The **vantage6** infrastructure is delivered in Docker images. To run these images, you need to have [Docker (docs.docker.com)](https://docs.docker.com/get-docker/) installed. To install the latest v
Sure, then not for trust but to show where they are leading. To me, making these links more clear is still far less important than the adverse effect it has on people being able to read through this paragraph easily. Note that this is one of the first places where people looking into vantage6 read about it, so I think it is important to write clearly here.

2024-11-04 09:58 UTC, frankcorneliusmartin commented on README.md
> +The **vantage6** infrastructure is delivered in Docker images. To run these images, you need to have [Docker (docs.docker.com)](https://docs.docker.com/get-docker/) installed. To install the latest v
Ok I yield. I also removed all other link targets from all other links in this readme.

2024-11-05 11:03 UTC, bartvanb approved these changes
Muy bien

2024-11-05 11:03 UTC, merged