Change/flexible api path store
vantage6/vantage6 pull request #1524
Opened 2024-10-08 15:16 UTC by bartvanb

Fix #1519

2024-10-21 09:52 UTC, frankcorneliusmartin requested changes

2024-10-21 09:52 UTC, frankcorneliusmartin commented on vantage6/vantage6/cli/configuration_wizard.py
> -    if include_api_path:
So do I get it right that the only way of setting this option is to manually set it? (Without using the wizard)? We also do it in a similar way for the vantage6-server? Why is it too complex here?

2024-10-21 09:52 UTC, frankcorneliusmartin commented on vantage6-backend-common/vantage6/backend/common/globals.py
> +DEFAULT_API_PATH = "/api"
I am thinking it might be better to make it a different default than the server? e.g. `/store`  or `/store-api`?

2024-10-25 11:52 UTC, bartvanb commented on vantage6/vantage6/cli/configuration_wizard.py
> -    if include_api_path:
There are many configuration options, so I think we should only ask users to configure the most important ones when doing `v6 [component] new`. I think configuring the API path is not important for most users - that's why I didn't include it in the wizard.

2024-10-25 11:52 UTC, bartvanb commented on vantage6/vantage6/cli/configuration_wizard.py
> -    if include_api_path:
That's btw also why the comment is there: in v5 I would personally prefer to also remove the option from the server for the interactive part.

2024-10-25 11:56 UTC, bartvanb commented on vantage6-backend-common/vantage6/backend/common/globals.py
> +DEFAULT_API_PATH = "/api"
I thought it would be simpler to keep them the same unless you run into issues - the more simple the easier to remember. And I don't think people will run into issues with them being the same: so far the store's API path was fixed at `/api`. 
Do you think people would run into issues and if so when? I think they are mostly avoided by using different ports locally and different URLs / nginx configs when deploying them

2024-10-29 16:12 UTC, frankcorneliusmartin commented on vantage6-backend-common/vantage6/backend/common/globals.py
> +DEFAULT_API_PATH = "/api"
I was thinking of all the poor people having to deal with NGINX configurations. This would promote using subpaths over subdomains. 

Anyway I don't really mind leaving it like this either. Feel free to merge it as is.

2024-10-29 16:14 UTC, frankcorneliusmartin commented on vantage6/vantage6/cli/configuration_wizard.py
> -    if include_api_path:
Maybe we should remove the wizard completely for all server components.

2024-10-29 16:14 UTC, frankcorneliusmartin approved these changes

2024-11-01 14:01 UTC, bartvanb commented on vantage6/vantage6/cli/configuration_wizard.py
> -    if include_api_path:
Indeed something to consider

2024-11-01 14:18 UTC, merged