Add option to set UI image in v6 dev network
vantage6/vantage6 pull request #1525
Opened 2024-10-08 15:34 UTC by bartvanb

Fix #1518

2024-10-21 09:53 UTC, frankcorneliusmartin requested changes

2024-10-21 09:53 UTC, frankcorneliusmartin commented on vantage6/vantage6/cli/dev/create.py
> +        extra_config += f"images:\n  ui: {ui_image}"
This wil break if `extra_config_file` already has a `images` section, right?

2024-10-25 12:00 UTC, bartvanb commented on vantage6/vantage6/cli/dev/create.py
> +        extra_config += f"images:\n  ui: {ui_image}"
Absolutely correct. I chose to ignore that in favour of having time to solve other things, as I don't think people will often run into that issue, and because it was not completely trivial to fix (now the extra config is read as simple text, then we have to parse as YAML and check that, and then convert back to text).

But I agree we should either solve it here or create a separate issue to fix later. I tend to prefer creating separate issue, what do you prefer?

2024-10-29 16:08 UTC, frankcorneliusmartin commented on vantage6/vantage6/cli/dev/create.py
> +        extra_config += f"images:\n  ui: {ui_image}"
I am fine with a seperate issue :)

2024-10-29 16:10 UTC, merged