Feature/policies algo store reviews
vantage6/vantage6 pull request #1634
Opened 2024-12-16 11:06 UTC by wbaccinelli

Closes #1365

2025-01-03 08:36 UTC, bartvanb requested changes
I'm very happy with this contribution. Most comments are pretty small but there are 2-3 slightly bigger ones. Let me know if you'd like to discuss those

2025-01-03 08:36 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/model/common/enums.py
> +    MIN_REVIEWING_ORGANIZATIONS = 2
I'm inclined to set the default values to 1 for the min reviews / min reviewing orgs. Maybe we should discuss this in standup.
(If we change it, unit tests should be changed as well)

2025-01-03 08:36 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/model/policy.py
> +            return 2
Please use the value from the default policies enum here

2025-01-03 08:36 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/model/policy.py
> +            return False
same here: use enum

2025-01-03 08:36 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/model/policy.py
> +            return 1
And also here and two more times below :-)

2025-01-03 08:36 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/model/user.py
> +        Email address
Thanks for adding this!

2025-01-03 08:36 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/review.py
> +def _is_reviewers_assignment_finished(reviews: list[db.Review]) -> bool:
Could you make this part of the class as such:

```
class ReviewBase:
    def _is_reviewers_assignment_finished()

class Reviews(ReviewsBase):

(etc)
```

We did it that way in a few other places so it's good to be consistent in that, plus I prefer to have the functions encapsulated

2025-01-03 08:36 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/review.py
> +                "msg": "You are not allowed to assign reviews."
To make it more clear for the user, could you extend this message to mention that there is a policy in place that allows only certain other users?

2025-01-03 08:36 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/review.py
> +                "msg": "You cannot assign reviewers for your own algorithm!"
Maybe here also, something like "This store does not allow developers to assign reviewers for their own algorithm"

2025-01-03 08:36 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/review.py
>                  "msg": f"User id='{reviewer.id}' is not allowed to review algorithms!"
And here again: could you split the `if` to send different message for denial based on either permission or policy?

2025-01-03 08:36 UTC, bartvanb commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/schema/input_schema.py
> +    organization = fields.Nested(OrganizationSchema, required=True)
I added this comment also elsewhere (in unit tests?), but it would be easier to just create an integer field `organization_id` here

2025-01-03 08:37 UTC, bartvanb commented on vantage6-algorithm-store/tests_store/resources/test_review.py
> +        )
After reviewing the rest of the code changes, I'm pretty sure the extra test will work but it's typically one of these things that might otherwise break in the future :-)

2025-01-10 09:03 UTC, bartvanb commented on vantage6-algorithm-store/tests_store/resources/test_policy.py
>                  value=f"http://localhost:{Ports.DEV_SERVER.value}/api",
Alternatively, we can create an issue to do this separately

2025-01-13 10:45 UTC, wbaccinelli commented on vantage6-algorithm-store/tests_store/resources/test_policy.py
>                  value=f"http://localhost:{Ports.DEV_SERVER.value}/api",
Sure, I will do this!

2025-01-13 10:51 UTC, wbaccinelli commented on vantage6-algorithm-store/tests_store/resources/test_review.py
> +        )
It's absolutely a good idea to add the extra test, I will do.

2025-01-13 12:56 UTC, wbaccinelli commented on vantage6-algorithm-store/tests_store/resources/test_review.py
> +        response = self.app.post("/api/review", headers=HEADERS, json=json_body)
No, this request is done by `assinger_2`, because it is the user returned by the mocked token validation. I make the comment more explanatory and change also the username to make it clearer.

2025-01-13 14:11 UTC, wbaccinelli commented on vantage6-algorithm-store/tests_store/resources/test_user.py
> +                    "data": [{"id": 1, "username": "mock", "organization": {"id": 1}}]
In this specific case, I'm mocking the response of the server, so I cannot change it, but you are totally right. I don't remember why I made it like this, but, looking back, it really doesn't a lot of sense. I'm simplifying it.

2025-01-13 14:19 UTC, wbaccinelli commented on vantage6-algorithm-store/vantage6/algorithm/store/__init__.py
> +                    db.Policy(key=policy, value=user.id).save()
Very good point, thank you for spotting this! I did not consider this scenario. I think that changing this to `username|server_url` will not require a lot of changes. 
 I will also remove the policy skipping.

2025-01-13 14:56 UTC, wbaccinelli commented on vantage6-algorithm-store/vantage6/algorithm/store/__init__.py
> +            root_organization = root_user.get("organization_id")
Indeed, well spotted!

2025-01-13 14:57 UTC, wbaccinelli commented on vantage6-algorithm-store/vantage6/algorithm/store/model/common/enums.py
> +    MIN_REVIEWING_ORGANIZATIONS = 2
Ok, let's briefly discuss this tomorrow morning.

2025-01-13 15:06 UTC, wbaccinelli commented on vantage6-algorithm-store/vantage6/algorithm/store/model/policy.py
> +            return 2
Yes, makes a lot of sense 😅

2025-01-13 15:12 UTC, wbaccinelli commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/review.py
> +def _is_reviewers_assignment_finished(reviews: list[db.Review]) -> bool:
Good suggestion, it's much neater in this way.

2025-01-13 15:17 UTC, wbaccinelli commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/review.py
> +                "msg": "You are not allowed to assign reviews."
Sure!

2025-01-13 15:21 UTC, wbaccinelli commented on vantage6-algorithm-store/vantage6/algorithm/store/resource/schema/input_schema.py
> +    organization = fields.Nested(OrganizationSchema, required=True)
Solved with the previous comment :)

2025-01-14 09:12 UTC, wbaccinelli commented on vantage6-algorithm-store/vantage6/algorithm/store/model/common/enums.py
> +    MIN_REVIEWING_ORGANIZATIONS = 2
Decided to stay with 2 as default.

2025-01-14 13:50 UTC, bartvanb approved these changes

2025-01-14 13:51 UTC, merged