change password endpoint
vantage6/vantage6 pull request #220
Opened 2022-06-29 11:33 UTC by bartvanb

Fix #210 

- New endpoint to change password using current password
- Changing password no longer possible via PATCH user
- Also made both changes for the Python client

2022-08-04 12:24 UTC, frankcorneliusmartin requested changes
Same changes that are mentioned in https://github.com/vantage6/vantage6/issues/59

2022-08-04 12:24 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/recover.py
> +            description: Current or new password is missing from JSON body
Or password match

2022-08-10 07:48 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/recover.py
> +            description: Current or new password is missing from JSON body
Done

2022-08-10 11:42 UTC, frankcorneliusmartin approved these changes

2022-08-10 11:51 UTC, merged