Removed deprecated verify argument from jwt decode; updated PyJWT version
vantage6/vantage6 pull request #227
Opened 2022-07-05 15:15 UTC by bartvanb

Fix #10

2022-08-04 11:54 UTC, frankcorneliusmartin requested changes

2022-08-04 11:54 UTC, frankcorneliusmartin commented on vantage6-client/requirements.txt
> +PyJWT
I would prefer to freeze the version

2022-08-04 11:54 UTC, frankcorneliusmartin commented on vantage6-client/setup.py
> +        'PyJWT',
Same for this one

2022-08-04 11:54 UTC, frankcorneliusmartin commented on vantage6-node/setup.py
> +            'PyJWT',
Aaaan this one

2022-08-05 14:38 UTC, frankcorneliusmartin commented
It seems something is not completely the same. This is from the server logs:
```python
Traceback (most recent call last):
  File "C:\\tools\\miniconda3\\envs\\work\\lib\\site-packages\\flask\\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\\tools\\miniconda3\\envs\\work\\lib\\site-packages\\flask\\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\\tools\\miniconda3\\envs\\work\\lib\\site-packages\\flask_restful\\__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\\tools\\miniconda3\\envs\\work\\lib\\site-packages\\flask\\views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "C:\\tools\\miniconda3\\envs\\work\\lib\\site-packages\\flask_restful\\__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\\tools\\miniconda3\\envs\\work\\lib\\site-packages\\flasgger\\utils.py", line 273, in wrapper
    return function(*args, **kwargs)
  File "C:\\Users\\FMa1805.36838\\Repositories\\vantage6\\vantage6-server\\vantage6\\server\\resource\\token.py", line 101, in post
    token = create_access_token(user)
  File "C:\\tools\\miniconda3\\envs\\work\\lib\\site-packages\\flask_jwt_extended\\utils.py", line 173, in create_access_token
    headers=headers)
  File "C:\\tools\\miniconda3\\envs\\work\\lib\\site-packages\\flask_jwt_extended\\jwt_manager.py", line 522, in _create_access_token
    headers=headers
  File "C:\\tools\\miniconda3\\envs\\work\\lib\\site-packages\\flask_jwt_extended\\tokens.py", line 77, in encode_access_token
    json_encoder=json_encoder, headers=headers)
  File "C:\\tools\\miniconda3\\envs\\work\\lib\\site-packages\\flask_jwt_extended\\tokens.py", line 30, in _encode_jwt
    json_encoder=json_encoder, headers=headers).decode(\'utf-8\')
AttributeError: \'str\' object has no attribute \'decode\'\
```

2022-08-05 14:58 UTC, frankcorneliusmartin commented
Also on the side note: 

```
vantage6-common

requirements.txt has additional requirements when compared to the setup.py file.
wincertstore==0.2
contextlib2==0.5.5
certifi==2020.4.5.1
```

2022-08-09 09:07 UTC, bartvanb reviewed
Looks good. Few additional suggestions.

2022-08-09 09:07 UTC, bartvanb commented on vantage6-server/tests_server/test_resources.py
>          return headers
I think this final return can now be deleted

2022-08-09 09:07 UTC, bartvanb commented on vantage6-server/vantage6/server/__init__.py
>              log.debug(traceback.format_exc())
We should consider turning this into `log.exception(error)` (and same 10 lines below)

2022-08-09 09:19 UTC, frankcorneliusmartin commented on Makefile
> +	coverage run --source=vantage6 --omit="utest.py","*.html","*.htm","*.txt","*.yml","*.yaml" utest.py
It already runs the unittests?

2022-08-09 09:23 UTC, frankcorneliusmartin commented on vantage6-client/requirements.txt
> +pandas
I do agree, however it is related to the pandas version in the algorithm container (or better the client version within the container). 

-> Seperate issue: https://github.com/vantage6/vantage6/issues/266

2022-08-09 09:24 UTC, frankcorneliusmartin commented on vantage6-server/tests_server/test_resources.py
>          return headers
Yes, I dont know why its still there :')

2022-08-09 09:24 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/__init__.py
>              log.debug(traceback.format_exc())
Yes!

2022-08-10 08:36 UTC, merged