Improved password and login requirements
vantage6/vantage6 pull request #231
Opened 2022-07-11 13:39 UTC by bartvanb

Better requirements for password, maximum number of login attempts and improved user feedback

Fix #59

2022-08-04 11:37 UTC, frankcorneliusmartin requested changes

2022-08-04 11:37 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/__init__.py
> +                # FIXME BvB 2022-08-01 only try refresh if 401 unauthorized?!
I agree that the token only needs to be refreshed when a 401 is returned. But for robustness it would be good to also retry when other error codes occur. If I am not mistaken, this happens also at other places in the code.

2022-08-04 11:37 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/__init__.py
> +            Either a username of email needs to be provided.
This does not make sense to me? It seems not the case in this method? And you are already logged in when using this method?

2022-08-04 11:37 UTC, frankcorneliusmartin commented on vantage6-server/tests_server/test_resources.py
> +    def create_user(self, organization=None, rules=[], password="password"):
Why supply a default password? If you want a default option, then I suggest to accept a `None` value and generate a solid password for them?

2022-08-04 11:37 UTC, frankcorneliusmartin commented on vantage6-server/tests_server/test_resources.py
> +    def create_user(self, organization=None, rules=[], password="password"):
Oh sorry nevermind me.. This is a testfile 👍

2022-08-04 11:37 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/globals.py
> +INACTIVATION_PERIOD_MINUTES = 15
I think it would even be nicer if these are overwritable in the config file.

2022-08-04 11:37 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/model/user.py
> +        new password to the database
Any particular reason we do not do that?

2022-08-04 11:37 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/model/user.py
> +        new password to the database
I get that if you do `user.password='something'` the user object is not saved. But I would expect `.set_password(...)` to also save it to the database?

2022-08-04 11:37 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/recover.py
> +
I am a little unconfortable with this being in the recover section. Would the `user` not be a better spot? Although I see that might be confusing with the PATCH on `/user/<id>`... A suggestion:

* PATCH `/user/<id>/password`
* PATCH  `/account/password`

Let me know what you think

2022-08-04 11:37 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/recover.py
> +            description: Current or new password is missing from JSON body
Or curent password matches new password

2022-08-04 14:02 UTC, bartvanb commented on vantage6-client/vantage6/client/__init__.py
> +                # FIXME BvB 2022-08-01 only try refresh if 401 unauthorized?!
Fair enough, good reason

2022-08-04 14:05 UTC, bartvanb commented on vantage6-client/vantage6/client/__init__.py
> +            Either a username of email needs to be provided.
Ctrl-C + Ctrl-V, and then forgot to change this...

2022-08-04 14:09 UTC, bartvanb commented on vantage6-server/vantage6/server/globals.py
> +INACTIVATION_PERIOD_MINUTES = 15
Yes that would be nicer indeed. Let me check if I can do that quickly, otherwise let's discuss if we do this now or later

2022-08-04 14:14 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/recover.py
> +
Also to me it didn't seem right for this to have the path `/recover/change`. On the other hand I do like this being in recover.py where we do all the other password/API key resets.
Maybe we can keep it in the same file but simply modify the endpoint name to make it PATCH `/account/password`

2022-08-04 14:15 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/recover.py
> +            description: Current or new password is missing from JSON body
And also: if new pw doesnt meet the requirements

2022-08-04 14:19 UTC, bartvanb commented on vantage6-server/vantage6/server/model/user.py
> +        new password to the database
Yes, I will adapt this. I guess I didn't do it because we do all of these `save()` actions in the resource folder. But this will then be the first `self.save()` we implement :-)

2022-08-04 14:22 UTC, bartvanb commented
I just incorporated most review comments, but there are two things left to do/discuss:
- where to put the change password endpoint code and what to name the endpoint
- make the number of password attempts and block time settable from the config file & wizard

2022-08-09 09:21 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/recover.py
> +            description: Current or new password is missing from JSON body
This is now also already updated on the branch where the change password endpoint is implemented

2022-08-09 09:44 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/recover.py
> +
Let's change this into `/password/change`

2022-08-09 11:30 UTC, bartvanb commented
You can now add the following in the config file to define how often a user can mistype their password and how long their account will be blocked when they do.
```    
password_policy:
    max_failed_attempts: 5
    inactivation_minutes: 15
```

2022-08-09 11:30 UTC, bartvanb commented on vantage6-server/vantage6/server/globals.py
> +INACTIVATION_PERIOD_MINUTES = 15
Added

2022-08-10 09:58 UTC, frankcorneliusmartin approved these changes

2022-08-10 11:15 UTC, merged