Implemented `wait_for_results` function in client
vantage6/vantage6 pull request #325
Opened 2022-10-03 13:50 UTC by bartvanb

Fix #8.

2022-10-10 15:08 UTC, frankcorneliusmartin commented
Can we remove this one: https://github.com/vantage6/vantage6/pull/192?

2022-10-10 15:08 UTC, frankcorneliusmartin requested changes

2022-10-11 07:23 UTC, bartvanb commented on vantage6-client/vantage6/client/__init__.py
> +        sys.stdout.write('\rDone!                  ')
I don't know of any nicer ways than `sys.stdout.flush()`, a quick google search doesn't give me nicer ways to flush output. Or do you mean the `sys.stdout.write()`? 
One option is to use the `rich` package as in #192 (otherwise that PR is outdated).

2022-10-18 14:46 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/__init__.py
> +        sys.stdout.write('\rDone!                  ')
Sorry I ment `clear` and not `flush`.. Geuss I was reading the line above it at the same time. I am oke with merging it as it is. But it would be nice to have a rich-er expierence 🥁

2022-10-18 14:48 UTC, frankcorneliusmartin approved these changes
Lets keep the rich stuff for later

2022-10-18 14:48 UTC, merged