Track which users initiate which tasks
vantage6/vantage6 pull request #326
Opened 2022-10-04 06:46 UTC by bartvanb

Fix #43 (except for the UI part which is a separate PR in the UI repo)

2022-10-18 14:39 UTC, frankcorneliusmartin reviewed
Could you also add the init user and org in the __repr__ function of the `model/task`?
Other than that it looks good to me!

2022-10-18 14:39 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/__init__.py
> +        def list(self, init_org_id: int = None, init_user_id: int = None,
I do find this a bit incosistent. We never specified that it needs to be an `_id`. So either we need to change that all enpoints or I would not start using it here.

2022-10-18 14:39 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/__init__.py
> +        def list(self, init_org_id: int = None, init_user_id: int = None,
Same goes for the user

2022-10-18 14:39 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/server_io.py
> +    def patch_results(self, id: int, init_org_id: int, result: dict):
Internally this is not an issue

2022-10-25 11:50 UTC, frankcorneliusmartin requested changes
Remove logging from the `only_for` decorator, as mentioned

2022-11-15 14:24 UTC, bartvanb commented on vantage6-client/vantage6/client/__init__.py
> +        def list(self, init_org_id: int = None, init_user_id: int = None,
Made this consistent

2022-11-15 14:24 UTC, bartvanb commented on vantage6-node/vantage6/node/server_io.py
> +    def patch_results(self, id: int, init_org_id: int, result: dict):
Left this the same - as it is not an issue

2022-11-16 11:00 UTC, frankcorneliusmartin approved these changes
lgtm

2022-11-16 11:00 UTC, merged