Logging endpoint on each request
vantage6/vantage6 pull request #329
Opened 2022-10-07 13:55 UTC by bartvanb

and which user/node/container is doing it (only for authenticated requests)

Fix #295

2022-10-10 14:54 UTC, frankcorneliusmartin requested changes
other than that it looks good

2022-10-10 14:54 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/__init__.py
> +                log.debug("Received request from container")
Can we also log the `node_id` and `task_id` from the container?

2022-10-11 11:43 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/__init__.py
> +                log.debug("Received request from container")
Added this.
Also, I added the request method and route to the logging in `resource/__init__.py` as that looked clearer in the logs. However, as we also log all request in the `@before_request` decorator, we now add two log messages for each request where JWT token is checked. Let's discuss what we want with that.

2022-10-25 11:46 UTC, frankcorneliusmartin approved these changes
Is the assumption safe that all the items always exists?

2022-10-25 11:47 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/__init__.py
> +                log.debug("Received request from container")
Why not remove the `f"Received request {request.method} {request.url_rule} "` from the `only_for` decorator?

2022-11-15 14:34 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/__init__.py
> +                log.debug("Received request from container")
We can remove the logging from `only_for` (and keep it only in `before_request`), but then we only know which requests are done, and not by whom

2022-11-15 14:39 UTC, bartvanb commented
> Is the assumption safe that all the items always exists?

I *think* so. `method` and `url_rule` seem to be reliable properties of a Flask request object (briefly checked the code). The other fields are in our own Sqlalchemy models so should also exist

2022-11-16 10:55 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/__init__.py
> +                log.debug("Received request from container")
I ment only remove the ` {request.method} {request.url_rule}` part from the logging. As it will be a duplicate with the line from `before_request`.

2022-11-16 11:07 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/__init__.py
> +                log.debug("Received request from container")
Ah clear. Just adapted it

2022-11-16 11:07 UTC, merged