Rewrite of socket connection functionality
vantage6/vantage6 pull request #417
Opened 2022-12-02 14:30 UTC by bartvanb

Fix #167 

- Introduced `status` field in results table that indicates stage of an algorithm
- Also added a status field to tasks which depends on underlying results
- Keeping track of these statuses via Socket events so database is up-to-date
- Added endpoint to kill task by task id
- Added endpoint to kill all tasks on a node
- New rules for these endpoints
- Added both of those options to Python client
- Refactored node socket namespace into separate file 
- Extended node socket namespace with events for new task, more task status events, and kill event
- Refactored server socket namespace to allow specific users into specific collaboration rooms

2022-12-12 13:12 UTC, frankcorneliusmartin requested changes
Overall it looks very nice.

2022-12-12 13:12 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/socket.py
> +class NodeTaskNamespace(ClientNamespace):
Maybe good to add types and docstrings?

2022-12-12 13:12 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/event.py
> +        tags: ["Kill tasks"]
Isn't this too specific? I feel this should be with `tasks`?

2022-12-12 15:38 UTC, bartvanb commented on vantage6-common/vantage6/common/docker/addons.py
> +        raise
Good point. I have moved the raise down to the try/except a few lines below, and checked that this raise is caught everywhere. 
Note that the docker hub issue is addressed here: #422

2022-12-12 15:39 UTC, bartvanb commented on vantage6-common/vantage6/common/task_status.py
> +class TaskStatus(Enum):
Cool, that makes sense

2022-12-12 15:43 UTC, bartvanb commented on vantage6-node/vantage6/node/__init__.py
> +        kill_list = kill_info.get('kill_list', None)
No the `kill_list` argument is only given if user requests to kill specific tasks. So it is not always defined

2022-12-12 15:54 UTC, bartvanb commented on vantage6-node/vantage6/node/docker/docker_manager.py
> +        kill_list: List[Dict]
Good idea

2022-12-13 08:35 UTC, bartvanb commented on vantage6-node/vantage6/node/server_io.py
> +            if not init_org_id:
But indeed it would be better to check if the collaboration is encrypted, and only raise an error if it is. But I think that's not a super easy fix so I'd say we make a separate issue out of that.

2022-12-13 08:51 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/event.py
> +        tags: ["Kill tasks"]
Yes I was struggling to decide there as well. Do we then also include `/kill/node/tasks` in the `Tasks`?

2022-12-13 08:51 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/event.py
> +        tags: ["Kill tasks"]
I'll do that for now

2022-12-13 10:56 UTC, bartvanb commented on vantage6-server/vantage6/server/model/task.py
> +            return TaskStatus.FAILED.value
Good suggestion! Funnily enough I could remove them in many places but not here: the API would then return a string 'TaskStatus.failed` instead of 'failed'. But in other places, where we stay within the vantage6 infra, I could remove the `.value`.

2022-12-13 12:53 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/event.py
> +        tags: ["Kill tasks"]
Yes, that makes sense to me

2022-12-13 12:56 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/model/task.py
> +            return TaskStatus.FAILED.value
It makes sense. But why is that object not oke?

2022-12-13 12:57 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/model/task.py
> +            return TaskStatus.FAILED.value
Then at some other point you required a string? Its not important, but I think the proper way is to leave it as an enum as long as possible.

2022-12-13 13:20 UTC, frankcorneliusmartin requested changes

2022-12-13 13:20 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/server_io.py
> +            if not init_org_id:
I looked at it a little closer. I think if we leave it like this it breaks the case when the init_org_id is not profided and when no encryption is used. 

https://github.com/vantage6/vantage6/blob/7277181df26ac487af9545f13546d2f912919dc1/vantage6-node/vantage6/node/server_io.py#L156-L168

The code is horrible (my mistake) but it supported the usecase by accident as 
` org = self.request(f"organization/None")` will just return a 404 and then the next try block is hit.

I am not completely sure if this is ever used though. So I assigned a new issue. #437

2022-12-13 13:20 UTC, frankcorneliusmartin commented on vantage6-common/vantage6/common/docker/addons.py
> +        pull = True
I still miss the changes for `if local_ and remote_`?

2022-12-13 13:20 UTC, frankcorneliusmartin commented on vantage6-common/vantage6/common/docker/addons.py
> +            raise docker.errors.APIError("Image not found") from e
I would say, `'failed to pull'` as it might also be other issues than a non existing image?

2022-12-13 13:45 UTC, frankcorneliusmartin approved these changes

2022-12-13 16:25 UTC, merged