Fix to pull docker images from docker hub if not found locally or remotely
vantage6/vantage6 pull request #432
Opened 2022-12-09 15:20 UTC by bartvanb

Fix #422

2022-12-12 14:00 UTC, frankcorneliusmartin commented
I am not sure if this is the solution. The command:

` client.container.run('hello-world')` pulls the image when it is not found locally. We should investigate why that is currently not the case in the infrastructure. 

The `pull_if_newer` method should only be used with an harbor instance.

2022-12-12 14:10 UTC, frankcorneliusmartin requested changes

2022-12-12 14:10 UTC, frankcorneliusmartin commented on vantage6-common/vantage6/common/docker/addons.py
>              log.warn(f"Local image is newer! Are you testing? {image}")
`pull = False`

2022-12-12 14:10 UTC, frankcorneliusmartin commented on vantage6-common/vantage6/common/docker/addons.py
>              log.warn(f"Local image is newer! Are you testing? {image}")
And remove the `pull=True` from the `remote_ > local_` case.

2022-12-12 14:10 UTC, frankcorneliusmartin commented on vantage6-common/vantage6/common/docker/addons.py
>              log.warn(f"Local image is newer! Are you testing? {image}")
add `pull=False` to the `remote_ == local_`

2022-12-12 14:10 UTC, frankcorneliusmartin commented on vantage6-common/vantage6/common/docker/addons.py
>          log.error(f"Cannot locate image {image}")
Maybe tell them we didn't find it on an Harbor instance?

2022-12-12 14:46 UTC, bartvanb commented on vantage6-common/vantage6/common/docker/addons.py
>              log.warn(f"Local image is newer! Are you testing? {image}")
instead, changed it back and added extra line that was missing before

2023-01-06 12:34 UTC, frankcorneliusmartin approved these changes
lgtm

2023-01-06 12:34 UTC, merged