Updated part of the docstrings of the server
vantage6/vantage6 pull request #466
Opened 2023-01-11 08:24 UTC by bartvanb

**Work-in-progress** let's merge this when all server docstrings are updated

2023-01-27 13:05 UTC, bartvanb commented on vantage6-server/vantage6/server/permission.py
> -
Note: we are deleting an unused function here!

2023-01-27 13:05 UTC, bartvanb commented on vantage6-server/vantage6/server/model/user.py
> -        return session.query(cls).all()
Note: we are deleting an unused function here!

2023-02-22 13:31 UTC, bartvanb commented
Let's see if we can merge this now - updating all server docstrings at once will only keep creating a lot of merge conflicts

2023-02-27 15:21 UTC, frankcorneliusmartin requested changes
That's a lot of docstrings

2023-02-27 15:21 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/permission.py
> +    def __init__(self, name) -> None:
Shouldnt we keep `RuleCollection` free from resources? Now it looks like (looks like) they need to be together (which is currently the case) but this is not strictly necessary. 

In the function `assign_rule_to_node` you changed all to resource, i would prefer to keep this as a collection (and this happens to be a resource collection). 

Buttttt, i also can live with this.

2023-02-27 15:21 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/permission.py
> +    def rule_exists_in_db(name, scope, operation) -> bool:
Typehints are missing

2023-02-27 15:21 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/permission.py
> +        Union[dict, bool]
Gehehe:  `|` looks so much better. Although this isn't wrong ofc.

2023-02-27 15:21 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/__init__.py
>  def only_for(types=['user', 'node', 'container']):
Typehint is missing `: list`

2023-02-27 15:21 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/__init__.py
> +def parse_datetime(dt=None, default=None) -> datetime:
Typehints are missing

2023-02-27 15:21 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/common/auth_helper.py
> +) -> Tuple[User | dict, HTTPStatus]:
Love this

2023-02-27 15:21 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/websockets.py
> +            algorithm was running
I understand this is due to the rendering(?). Cant we display a small example?:
```
{
    "node_id": 1,
    ...
}

2023-02-27 15:23 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/model/user.py
> -        return session.query(cls).all()
Also remote the rest in `test_models.py` L:95 - `assert User.get_user_list()`

2023-02-27 15:38 UTC, bartvanb commented on vantage6-server/vantage6/server/__init__.py
> +with the database to store which organizations, collaborations, users, etc.
done

2023-02-27 15:41 UTC, bartvanb commented on vantage6-server/vantage6/server/__init__.py
> +        Configuration environment. Default value is 'prod'.
done

2023-02-27 15:43 UTC, bartvanb commented on vantage6-server/vantage6/server/model/__init__.py
> +from .authenticatable import Authenticatable
done

2023-02-27 15:48 UTC, bartvanb commented on vantage6-server/vantage6/server/model/organization.py
> +    def public_key(self, public_key_b64) -> None:
added

2023-02-27 15:49 UTC, bartvanb commented on vantage6-server/vantage6/server/model/permission.py
> +The Userpermission table defines which extra rules have been assigned to which
Camelcased

2023-02-27 15:49 UTC, bartvanb commented on vantage6-server/vantage6/server/model/role.py
> +    def get_by_name(cls, name) -> Union[Role, None]:
done

2023-02-27 15:51 UTC, bartvanb commented on vantage6-server/vantage6/server/model/rule.py
> +    scope and resource on which it acts.
nice one :-)

2023-02-28 12:45 UTC, merged