Added new endpoint /vpn/algorithm/addresses to retrieve the IP addres…
vantage6/vantage6 pull request #501
Opened 2023-01-19 16:28 UTC by bartvanb

…ses + ports of other algorithm containers in the same task

Fix #499

2023-01-27 10:21 UTC, frankcorneliusmartin requested changes
lgtm.

However shouldnt we return an error code when no VPN is configured?

2023-01-27 10:21 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/__init__.py
> +                # get an error message with 403(?) code
No I actually think this is a bad request? 

As it is not an authentication failure, but input that is not allowed making it a bad request in my opinion.

2023-01-27 10:21 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/__init__.py
> +                # get an error message with 403(?) code
The message bellow is then also incorrect. it should  be something like: 
`unrecognised type: {g.type}`

2023-01-31 10:42 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/__init__.py
> +                # get an error message with 403(?) code
I agree with the former, so I have updated the comment to say code 400. 
However, the second comment is incorrect: the `types` variable does not always contain all types. E.g. if `types=['user']` and a node attempts to use the endpoint, the message is correct (just verified this to be sure)

2023-02-09 13:34 UTC, frankcorneliusmartin approved these changes
lgtm

2023-02-09 13:35 UTC, merged