Feature/updated algorithm client
vantage6/vantage6 pull request #510
Opened 2023-01-27 09:34 UTC by bartvanb

Fix #493

2023-01-27 10:41 UTC, frankcorneliusmartin requested changes
Nice solution with the `use_new_client`.
Maybe something that we can in the decorator as well ^.^
`@AlgorithmClient(version=1)`

Ofc. I did not check the VPN changes

2023-01-27 10:41 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/algorithm_client.py
> +            name = subtask or "subtask"
Why not make this as a default in the argument? `subtask: str = "subtask"`

2023-01-27 10:41 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/client/algorithm_client.py
> +            return results['addresses']
Since you are not passing the output of the request directly, this could raise an exception. 

Check that the key is present or the status code. But I dont think we want to raise an exception here.

2023-01-31 10:47 UTC, bartvanb commented on docs/algorithms/classic_tutorial.rst
> -    The ``client`` the master method receives is a ``ContainerClient`` which is
Yeah true, at least if we can find a way in v4. I guess I was a bit lazy in updating the docs - I'll update this

2023-01-31 10:49 UTC, bartvanb commented on vantage6-client/vantage6/client/algorithm_client.py
> +            """
Added

2023-01-31 10:51 UTC, bartvanb commented on vantage6-client/vantage6/client/algorithm_client.py
> +            name = subtask or "subtask"
good point

2023-01-31 10:55 UTC, bartvanb commented on vantage6-client/vantage6/client/algorithm_client.py
> +            return results['addresses']
Added check on the presence of the key, otherwise sending a message back to the algorithm.

2023-02-09 13:38 UTC, frankcorneliusmartin approved these changes
lgtm

2023-02-09 13:38 UTC, merged