Change/specific operations send receive socket
vantage6/vantage6 pull request #516
Opened 2023-02-01 15:10 UTC by bartvanb

Fix #402 

- Created new operations 'send' and 'receive' for socket rules
- Changed socket rules to reflect new operations
- Changes in endpoints to reflect changes in rules
- Removed the 'complete' property from db.Task which is superseded by 'status', but kept a function in its stead as that is used elsewhere
- Remove unused function

2023-02-09 13:16 UTC, frankcorneliusmartin requested changes

2023-02-09 13:16 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/model/task.py
> -    @hybrid_property
Shouldn't the entire function `complete` be deleted?

2023-02-09 13:16 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/task.py
> +        if db.Task.get(container["task_id"]).complete():
Why not use the `task.status` for this?

2023-02-09 13:16 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/token.py
> +        if db_task.complete():
Same for this one

2023-02-10 09:13 UTC, bartvanb commented on vantage6-server/vantage6/server/model/task.py
> -    @hybrid_property
I have done a new commit that should address this comment and the comments below.
This property has now been fully removed, and in other places now making use of the `has_task_finished()` function from vantage6-common. Also, I removed the same property in the `result` class.

2023-02-10 09:13 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/task.py
> +        if db.Task.get(container["task_id"]).complete():
See above

2023-02-10 09:13 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/token.py
> +        if db_task.complete():
See above

2023-02-22 10:48 UTC, frankcorneliusmartin approved these changes

2023-02-22 10:48 UTC, merged