Feature/multi data source wrapper
vantage6/vantage6 pull request #555
Opened 2023-02-27 12:51 UTC by frankcorneliusmartin

Issue: #553

2023-02-27 14:20 UTC, bartvanb requested changes
Very cool improvement. I had quite a few comments but they are pretty minor or docs-related

2023-02-27 14:20 UTC, bartvanb commented on vantage6-client/vantage6/tools/wrapper.py
> +DockerWrapper = CSVWrapper
Maybe add a note that this is only here for backwards compatiblity, to make it clear in the future why this is here

2023-02-27 14:20 UTC, bartvanb commented on vantage6-client/vantage6/tools/wrapper.py
> +    def load_data(database_uri, *_):
Add note to remove the unnecessary args in v4? I think that would be good, since algorithm devs will need to update the algo's anyway for v4.

2023-02-27 14:20 UTC, bartvanb commented on vantage6-client/vantage6/tools/wrapper.py
> +    def load_data(database_uri, input_data):
For all these wrappers: docstrings and type hints

2023-02-27 14:20 UTC, bartvanb commented on vantage6-common/vantage6/common/__init__.py
> +        "info": f"[{Fore.GREEN}info {Style.RESET_ALL}]",
I'm curious why you made this change :-)

2023-02-27 14:20 UTC, bartvanb commented on vantage6-common/vantage6/common/__init__.py
> +        List of database configurations
arg order is different from function definition

2023-02-27 14:20 UTC, bartvanb commented on vantage6-common/vantage6/common/__init__.py
> +    ]
Can you also add this to the user docs in the node config section?

2023-02-27 14:20 UTC, bartvanb commented on vantage6-node/vantage6/node/docker/docker_manager.py
> +                db_type = db_config['type']
You could move this line outside of the `if` since it's the same 2 times

2023-02-27 14:20 UTC, bartvanb commented on vantage6-client/vantage6/tools/wrapper.py
> +compatible with the ``smart_wrapper``.
I see this called `smart_wrapper` here but below it is `auto_wrapper`. These are the same right? (Btw I prefer auto_wrapper)

2023-02-27 14:27 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/tools/wrapper.py
> +        label = os.environ["USER_REQUESTED_DATABASE_LABEL"]
It means that new algorithms build with this wrapper are not compatible with >v3.8. I dont think this has anything to do with the server?

2023-02-27 14:28 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/docker_manager.py
> +    def _set_database(self, databases: Union[Dict, List]) -> None:
I know! I just found out while doing your review =]

2023-02-27 15:52 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/tools/util.py
> -    sys.stdout.write("error > "+msg+"\n")
Ok I also added some docstrings

2023-02-27 15:55 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/tools/wrapper.py
> +        label = os.environ["USER_REQUESTED_DATABASE_LABEL"]
Nodes do print an error when this happens, this ends up in the log files which are send to the user.

2023-02-27 15:58 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/tools/wrapper.py
> +compatible with the ``smart_wrapper``.
Good catch. I changed it half way through the development

2023-02-27 16:29 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/tools/wrapper.py
> +    def load_data(database_uri: str, input_data):
I added typehints to the entire file

2023-02-27 16:29 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/tools/wrapper.py
> +DockerWrapper = CSVWrapper
Done

2023-02-27 16:29 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/tools/wrapper.py
> +    def load_data(database_uri, input_data):
Yes!

2023-02-27 16:30 UTC, frankcorneliusmartin commented on vantage6-common/vantage6/common/__init__.py
> +        "info": f"[{Fore.GREEN}info {Style.RESET_ALL}]",
I hated how the lines jumped with the logging. Looks so much better now :P

2023-02-27 16:30 UTC, frankcorneliusmartin commented on vantage6-common/vantage6/common/__init__.py
> +        List of database configurations
Good catch, i changed that later

2023-02-27 16:31 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/docker_manager.py
> +                db_type = db_config['type']
ty

2023-02-27 16:33 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/tools/wrapper.py
> +    def load_data(database_uri, *_):
Linters complain when the signature is not the same from the abstract parent method (which make sense). So I dont think we can remove them. (Or we should change the abstract function

2023-02-28 08:22 UTC, bartvanb commented on vantage6-client/vantage6/tools/wrapper.py
> +        label = os.environ["USER_REQUESTED_DATABASE_LABEL"]
Yeah you're right, that seems quite alright then

2023-02-28 08:40 UTC, bartvanb commented on vantage6-client/vantage6/tools/wrapper.py
> +    def load_data(database_uri, *_):
fair enough

2023-02-28 08:41 UTC, bartvanb commented on vantage6-common/vantage6/common/__init__.py
> +        "info": f"[{Fore.GREEN}info {Style.RESET_ALL}]",
Ah nice :-)

2023-02-28 08:47 UTC, bartvanb requested changes
Nice changes, I only have 1 comment about docstrings

2023-02-28 08:47 UTC, bartvanb commented on vantage6-client/vantage6/tools/wrapper.py
> +    def load_data(database_uri: str, input_data: dict) -> pandas.DataFrame:
missing docstring, here and in other functions below

2023-02-28 08:48 UTC, bartvanb commented on vantage6-common/vantage6/common/__init__.py
> +    ]
nice

2023-02-28 08:50 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/tools/wrapper.py
> +    def load_data(database_uri: str, input_data: dict) -> pandas.DataFrame:
It has docstrings from there abstract class, we could overwrite them but that would result in dulplication

2023-02-28 14:33 UTC, bartvanb approved these changes
One very minor comment, but already pre-approved it.

2023-02-28 14:33 UTC, bartvanb commented on vantage6-client/vantage6/tools/wrapper.py
> +        Load the local (privacy sensitive) data from the database.
`privacy-sensitive` (and I'd prefer without the brackets)

2023-02-28 14:33 UTC, bartvanb commented on vantage6-client/vantage6/tools/wrapper.py
> +        Load the local (privacy sensitive) data from the database.
(Also change in the other ones of course)

2023-02-28 14:40 UTC, frankcorneliusmartin commented on vantage6-client/vantage6/tools/wrapper.py
> +        Load the local (privacy sensitive) data from the database.
Done

2023-02-28 14:42 UTC, merged