Option to set allowed users and orgs on a node
vantage6/vantage6 pull request #556
Opened 2023-02-27 14:53 UTC by bartvanb

Fix #335

2023-02-27 15:46 UTC, frankcorneliusmartin requested changes

2023-02-27 15:46 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/docker_manager.py
> +            if isinstance(allowed_algorithms, str):
why would we support this? I think it should _always_ be a list

2023-02-27 15:46 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/server_io.py
> +                pass
why not `user_allowed = init_user_id in allowe_users`?

2023-02-27 15:46 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/server_io.py
> +                pass
Is this some co-pilot suggestion?

2023-02-27 16:18 UTC, bartvanb commented on vantage6-node/vantage6/node/server_io.py
> +                pass
Oh wait... list comprehension wouldn't work if somebody gives a list like `['frank', '33']` for allowed users because it would fail on the first one. And in python `'1' == 1` resolves to `False` so we need the cast to int

2023-02-27 16:18 UTC, bartvanb commented on vantage6-node/vantage6/node/server_io.py
> +        for org in allowed_orgs:
See above

2023-02-28 08:40 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/docker_manager.py
> +            if isinstance(allowed_algorithms, str):
Meh. Only card I have is that it adds ugly code.

2023-02-28 12:39 UTC, bartvanb commented on vantage6-node/vantage6/node/server_io.py
> +                pass
Now changed this to cast to string instead of to int, so we don't need the try/except

2023-02-28 12:52 UTC, merged