Docs/features
vantage6/vantage6 pull request #588
Opened 2023-03-08 16:43 UTC by bartvanb

Updates to features in tech docs

2023-03-10 08:39 UTC, frankcorneliusmartin requested changes
Great work

2023-03-10 08:39 UTC, frankcorneliusmartin commented on docs/technical-documentation/features/inter-component/socket.rst
> +    with the server when the user logs in. The user is then
The user is then what? ;-)

2023-03-10 08:39 UTC, frankcorneliusmartin commented on docs/technical-documentation/features/inter-component/vpn.rst
> +allow algorithm containers to communicate directly with one another.
Lets add that in some protocols the traffic between parties can not be shared with other parties. As in this case this 'central' party will be able to reconstruct the original data. For example in the MPC protocol.

2023-03-13 15:12 UTC, bartvanb commented on docs/technical-documentation/features/inter-component/socket.rst
> +    with the server when the user logs in. The user is then
:"-) I think I wanted to say something about permissions. I now changed it into "The user can then view the updates
    they are allowed to see."

2023-03-13 15:16 UTC, bartvanb commented on docs/technical-documentation/features/inter-component/vpn.rst
> +allow algorithm containers to communicate directly with one another.
Added a paragraph

2023-03-13 15:17 UTC, bartvanb commented on docs/technical-documentation/features/inter-component/vpn.rst
> +If you are using the Python algorithm client, you can call the following
No because that unfortunately doesn't exist yet...

2023-03-20 11:07 UTC, bartvanb commented on docs/technical-documentation/features/inter-component/vpn.rst
> +If you are using the Python algorithm client, you can call the following
No, what I mean is that we don't have documentation on the API of the client yet. So then I can't refer to that in the docs

2023-03-20 11:08 UTC, frankcorneliusmartin commented on docs/technical-documentation/features/inter-component/vpn.rst
> +If you are using the Python algorithm client, you can call the following
Ah makes sense.

2023-03-20 11:08 UTC, frankcorneliusmartin approved these changes

2023-03-20 11:08 UTC, merged