Feature/whitelisting with squid
vantage6/vantage6 pull request #626
Opened 2023-04-19 07:45 UTC by frankcorneliusmartin

2023-04-26 11:44 UTC, dsmits requested changes
Looks good, some minor changes

2023-04-26 11:44 UTC, dsmits commented on vantage6-node/vantage6/node/docker/squid.py
> +        safe_ips = safe_ips + ["172." + str(i) + "." for i in range(16, 32)]
are these the ip's docker gives to containers? Could you add a comment to explain?

2023-04-26 11:44 UTC, dsmits commented on vantage6-node/vantage6/node/docker/squid.py
> +    ports: list[int]
Don't you want to whitelist ports in combination with an ip or domain? Why is this a separate list?

2023-04-26 11:44 UTC, dsmits commented on vantage6-node/vantage6/node/docker/squid.py
> +        """
I would add in the docstring an explanation of what is considered safe. Or is this explained elsewhere in the documentation?
As I understand the whitelist is considered safe in the following situations:
- If it contains domains, only port 443 should be allowed
- The ip's are all on local networks:
  - 10.something (vpn)
  - 192.168.something (lan)
  - 172. something (ip's on localhost for local docker containers)

2023-04-26 11:44 UTC, dsmits commented on vantage6-node/vantage6/node/docker/task_manager.py
> +                # network = ipaddress.IPv4Network(
I guess this commented out code can be removed?

2023-05-01 15:07 UTC, bartvanb requested changes
Very nice, all minor stuff I think

2023-05-01 15:07 UTC, bartvanb commented on vantage6-node/vantage6/node/docker/task_manager.py
> +            environment_variables["https_proxy"] = self.proxy.address
maybe good also to repeat here why multiple envvars are required

2023-05-01 15:07 UTC, bartvanb commented on vantage6-node/vantage6/node/proxy_server.py
> +to access other places in the network.
Nice!

2023-05-01 15:07 UTC, bartvanb commented on vantage6-node/vantage6/node/template/squid.conf.j2
> +http_port 3128
Is there a reason to pick this port? Should we do any checks to ensure it's free?

2023-05-04 08:23 UTC, frankcorneliusmartin commented on Makefile
I looked at some alternatives, but Squid seemed to be the mostly used and it is open source.

2023-05-04 08:28 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/squid.py
> +        safe_ips = safe_ips + ["172." + str(i) + "." for i in range(16, 32)]
Internal refers to the dedicated ranges for internal networking: https://en.wikipedia.org/wiki/Private_network

The VPN traffic is NOT routed through the proxy by setting the `NO_PROXY` environment variable. This is documented in the docs.

I added additional comments to explain all this in de code also.

2023-05-04 08:30 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/squid.py
> +    ports: list[int]
Excelent question =]. I also looked for this because that would be a much better setup. Unfortunately this is not supported by squid, see for example this thread (https://www.linuxquestions.org/questions/linux-newbie-8/squid-allow-one-ip-on-a-particular-port-4175593695/)

2023-05-04 09:28 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/squid.py
> +        """
The whitelist not considered safe if it contains domains and non-https ports. Also, the whitelist is not considered safe if it contains non-internal IP addresses.

Note that the 10.x.x.x is also internal and not the VPN. As mentioned in the previous comment, the VPN traffic is not routed through this proxy service.

2023-05-04 09:33 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/task_manager.py
> +                # network = ipaddress.IPv4Network(
I changed the comment why we did it like this and removed the commented out code

2023-05-04 11:36 UTC, frankcorneliusmartin commented on docker/squid.Dockerfile
> +FROM debian:10
Lets make a separate issue for this as this is the basic for more support images: https://github.com/vantage6/vantage6/issues/639

2023-05-04 11:37 UTC, frankcorneliusmartin commented on docs/node/node_config.yaml
> +
Unfortunately this is not possible in squid. If you whitelist a port it is whitelisted for all domain and ips you specified.

2023-05-04 11:44 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/__init__.py
> +
Dont know what happend here.. but docstring is added.

2023-05-04 11:46 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/__init__.py
> +            self.log.error("Error setting up Squid proxy")
Yes! I also upgraded it from `error` to `critical` as this could break things..

2023-05-04 11:47 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/squid.py
> +can be created, each with a different configuration.
Why would you say that. LOL

2023-05-04 11:50 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/squid.py
> +        self.port = 3128
Yes this is indeed the default port of squid (no need to change this as we control the private network). Added docstring to explain this

2023-05-04 11:55 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/squid.py
> +    def address(self) -> str:
Aye

2023-05-04 11:59 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/task_manager.py
> +            environment_variables["https_proxy"] = self.proxy.address
Added additional comment to highlight it

2023-05-04 12:01 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/template/squid.conf.j2
> +http_port 3128
Why we are only running the squid in this container. This is the port the container self listens to. So there will never be a conflict here.

2023-05-04 14:32 UTC, dsmits approved these changes
Looks good to me

2023-05-08 08:35 UTC, bartvanb commented on docs/node/node_config.yaml
> +
Ok in that case, can we clearly state in the docs that this is the case?

2023-05-08 08:36 UTC, bartvanb commented on docs/node/node_config.yaml
> +
Ah I saw you already did that

2023-05-08 08:53 UTC, bartvanb approved these changes
You addressed all comments perfectly :-)

2023-05-08 14:48 UTC, merged