Prevent that tasks are killed if socket connection is temporarily lost
vantage6/vantage6 pull request #640
Opened 2023-05-04 13:29 UTC by bartvanb

Fix #637

2023-05-08 08:23 UTC, bartvanb commented
.... aaaand fixes #638 as well (I think, still need to test)

2023-05-08 14:47 UTC, frankcorneliusmartin requested changes
Request for one additional log line, other than that it looks good

2023-05-08 14:47 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/__init__.py
> +                retries < MAX_ATTEMPTS:
Could you add a log here that states something like `waiting for namespace to connect?`

2023-05-09 07:17 UTC, frankcorneliusmartin approved these changes

2023-05-09 07:25 UTC, merged