Feature/control individual log levels
vantage6/vantage6 pull request #642
Opened 2023-05-08 13:09 UTC by frankcorneliusmartin

2023-05-09 07:21 UTC, bartvanb requested changes
Good improvement, just a few minor comments

2023-05-09 07:21 UTC, bartvanb commented on docs/node/node_config.yaml
> +    proxy_server: true
Shouldn't we have these by default at false?

2023-05-09 07:21 UTC, bartvanb commented on docs/server/yaml/server_config.yaml
> +
same as above

2023-05-09 07:21 UTC, bartvanb commented on docs/node/node_config.yaml
> +    proxy_server: true
And would it make sense to add 1 indent? And should we list all the options for packages? (I think it's just 'flask' missing right?)

2023-05-23 12:53 UTC, frankcorneliusmartin commented on docs/node/node_config.yaml
> +    proxy_server: true
Made them by default False. Identation does not make sense to me as the logging session refers to the configuration of the  python logger.

2023-05-23 13:25 UTC, merged