Docs/api references extended
vantage6/vantage6 pull request #668
Opened 2023-05-15 08:31 UTC by bartvanb

This adds the API references for cli/common/client and adds extra to existing node/client API refs

2023-05-22 13:04 UTC, frankcorneliusmartin requested changes
Lot of work Bart! Let merge this into 3.9 as we want to test is sufficiently

2023-05-22 13:04 UTC, frankcorneliusmartin commented on vantage6-common/vantage6/common/configuration_manager.py
> +    ) -> 'ConfigurationManager':
See comment about classmethod return types

2023-05-22 13:04 UTC, frankcorneliusmartin commented on vantage6-common/vantage6/common/context.py
> +    def environment(self, env) -> None:
Type `str`missing

2023-05-22 13:04 UTC, frankcorneliusmartin requested changes
Lot of work Bart! Let merge this into 3.9 as we want to test is sufficiently

2023-05-22 14:56 UTC, bartvanb commented on tools/update-version.py
> +)
This is actually a change in release/3.9. So not sure how that ended up here.

2023-05-22 15:06 UTC, bartvanb commented on vantage6-client/vantage6/client/algorithm_client.py
> +                List of organization IDs that should execute the task.
Well it still has a default value.. but specifying zero organizations doesn't make sense. A task for 0 orgs will never be executed by anyone so why create it?

2023-05-22 15:10 UTC, bartvanb commented on vantage6-client/vantage6/tools/dispatch_rpc.py
> +def dispatch_rpc(data: Any, input_data: dict, module: ModuleType, token: str,
You're right, it should be str. It is used to obtain a ModuleType and I guess I misread

2023-05-22 15:20 UTC, bartvanb commented on vantage6-server/vantage6/server/cli/server.py
> +    Note that using the shell is not recommended, as there are no checks on
Nice addition, done!

2023-05-23 07:05 UTC, bartvanb commented on vantage6-server/vantage6/server/context.py
> +    def from_external_config_file(cls) -> 'TestContext':
this has been deleted there in 3.9

2023-05-23 07:52 UTC, merged