Feature/collaboration scope
vantage6/vantage6 pull request #711
Opened 2023-06-14 13:33 UTC by bartvanb

Fix #245

2023-07-03 11:52 UTC, bartvanb commented
Ignore codacy

2023-07-14 07:09 UTC, frankcorneliusmartin requested changes

2023-07-14 07:23 UTC, bartvanb commented on vantage6-server/vantage6/server/permission.py
> +        global_perm = getattr(self, f'{operation.value}_{Scope.GLOBAL.value}')
Yes I added `str` to the Enum (both Operation and Scope) and checked that it works

2023-07-14 07:26 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/__init__.py
> +        return [
This function is not really used for permission checks. An example where it is used: when someone requests roles with `collaboration_id=x`, this function is used to determine which organization ids have to be put in the query filter.

2023-07-14 08:20 UTC, bartvanb commented on vantage6-server/vantage6/server/permission.py
> +        auth: Authenticatable
True, I made a utils function to get auth's collaborations and also did the same for organizations
Indeed this makes endpoints much cleaner again :-)

2023-07-14 08:27 UTC, frankcorneliusmartin approved these changes

2023-07-14 08:52 UTC, merged