Feature/request validation marshmallow
vantage6/vantage6 pull request #744
Opened 2023-07-03 10:06 UTC by bartvanb

Fix #76

2023-07-13 09:00 UTC, frankcorneliusmartin requested changes
Minor comments, other than that it looks good! Nice enhancement of the API

2023-07-13 09:00 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/common/input_schema.py
Return `-> None` are missing

2023-07-13 09:00 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/common/input_schema.py
> +            if 'input' not in organization:
I dont think this is per-se the case? What if you just want to send a container without any input?

2023-07-13 09:00 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/common/input_schema.py
I think this looks really nice

2023-07-13 09:00 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/port.py
> +        run_id = data.get('run_id')
Wont this break the filter bellow? Or is is guaranteed to be there because of the schema validation? In this case I would like it to be `data['run_id']` as this make this assumption explicit

2023-07-13 09:00 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/recover.py
> +        id_ = body.get('id')
I think `id` is garanteed, so use square brackets here also

2023-07-13 09:00 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/user.py
> +        if data.get("firstname") is not None:
I prefer `if not data.get("firstname")` over the `is` comparison. In this case it works, as `None` always refers to the same spot in memory..

2023-07-13 11:08 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/common/input_schema.py
:-)

2023-07-13 11:18 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/common/input_schema.py
> +    def validate_email_or_username(self, data: dict, **kwargs):
You mean whether it is a valid email / username or if it is an email / username that exists in the database? The latter is always checked in the endpoints, and I think we should keep doing it there (e.g. non-existing user should give 404, not 400). 
If you mean the former, it is validated if something is an email by specifying `fields.Email()` two lines above this comment. 
Then, we could validate the username further by using the function `_validate_name()`, but I think in this particular case we have an endpoint to recover a password, and then you should put an existing username. I think we don't necessarily want to tell here that the username is invalid.

2023-07-13 11:23 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/common/input_schema.py
> +            if 'input' not in organization:
The 'input' always contains at least the `method` field that describes which algorithm to run, so there should always be an input field. But maybe we should change that, and give the method a separate field? Or do we envision a case where one task may call different methods for different organizations?
If we do change this, perhaps make a separate issue?

For now, I added a check if the `input` field contains a `method` field

2023-07-13 11:30 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/user.py
> +        if data.get("firstname") is not None:
No, we actually changed it to this a few months ago for a good reason: if you patch a user and you want to give them `firstname=''`, with this check it would work. With the check you suggest, it wouldn't work because an empty string would evaluate to False

2023-07-14 07:00 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/common/input_schema.py
> +            if 'input' not in organization:
You are assuming the wrapper is used, I don't think we should force it.

2023-07-14 07:06 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/common/input_schema.py
> +            if 'input' not in organization:
You're right indeed, good point!

2023-07-14 07:09 UTC, frankcorneliusmartin approved these changes

2023-07-14 07:15 UTC, merged