Add flag whether linked resources should be deleted in delete endpoin…
vantage6/vantage6 pull request #748
Opened 2023-07-05 15:50 UTC by bartvanb

…ts that affect other resources

2023-07-11 07:55 UTC, frankcorneliusmartin requested changes

2023-07-11 07:55 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/task.py
> +        for child_task in task.children:
I think this should be recursive as this would only delete the first level of children but there could be more.

2023-07-11 13:33 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/task.py
> +        for child_task in task.children:
Done

2023-07-14 07:02 UTC, frankcorneliusmartin requested changes

2023-07-14 07:12 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/task.py
> +    def _delete_child_tasks(task: db.Task):
done

2023-07-14 07:12 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/task.py
>          # delete child tasks
I put `child/grandchild/...` in the comment and renamed function to `delete_subtasks`

2023-07-14 07:14 UTC, frankcorneliusmartin approved these changes

2023-07-14 08:32 UTC, merged

2023-09-13 12:55 UTC, frankcorneliusmartin commented
✅ roles (not available in the python client)
```python
>>> client.request('role/11', method='delete', params={'delete_dependents': True})
Making request: DELETE | http://localhost:5000/api/role/11 | {'delete_dependents': True}
Starting new HTTP connection (1): localhost:5000
http://localhost:5000 "DELETE /api/role/11?delete_dependents=True HTTP/1.1" 200 42
{'msg': 'Role removed from the database.'}
```
✅ task (subtasks are always deleted)
```python
>>> client.request('task/8', method='delete')
Making request: DELETE | http://localhost:5000/api/task/8 | None
Starting new HTTP connection (1): localhost:5000
http://localhost:5000 "DELETE /api/task/8 HTTP/1.1" 200 78
{'msg': 'task id=8 and its algorithm run data have been successfully deleted'}
```
✅ user (not available in the python client)
```python
>>> client.request('user/1', method='delete', params={'delete_dependents': True})
Making request: DELETE | http://localhost:5000/api/user/1 | {'delete_dependents': True}
Starting new HTTP connection (1): localhost:5000
http://localhost:5000 "DELETE /api/user/1?delete_dependents=True HTTP/1.1" 200 49
{'msg': 'user id=1 is removed from the database'}
```
✅ collaboration (not available in the python client)
```python
>>> client.request('collaboration/1', method='delete', params={'delete_dependents': True})
Making request: DELETE | http://localhost:5000/api/collaboration/1 | {'delete_dependents': True}
Starting new HTTP connection (1): localhost:5000
http://localhost:5000 "DELETE /api/collaboration/1?delete_dependents=True HTTP/1.1" 200 50
{'msg': 'Collaboration id=1 successfully deleted'}
```