Docs/algorithm documentation
vantage6/vantage6 pull request #754
Opened 2023-07-11 12:58 UTC by bartvanb

2023-07-13 09:46 UTC, frankcorneliusmartin requested changes

2023-07-13 09:46 UTC, frankcorneliusmartin commented on docs/algorithms/concepts.rst
> +analysis.
1. orchestration != aggregation
2. I would stay away here from using the word federated

> Multi-party analyses commonly have an orchestator/aggregator and a remote part,
> where the aggregator part is responsible for combining the partial results of
> the remote part, ~~and the federated part is responsible for the actual
> analysis.~~

2023-07-13 09:46 UTC, frankcorneliusmartin commented on docs/algorithms/concepts.rst
I think we should move away from federated in this concepts section as it is also the same for MPC and HE. We should come up with some container _roles_ (ochestrator, aggregator, partial?, ...) to make this section more general

2023-07-13 09:46 UTC, frankcorneliusmartin commented on docs/algorithms/concepts.rst
> +    information, see `here <https://vantage6.ai/news/algorithm-journey/>`_.
I think the information of this blog should also be in this documentation.

2023-07-13 09:46 UTC, frankcorneliusmartin commented on docs/algorithms/concepts.rst
> +internet while they are running.
remove 'while they are running' is only adds confusion. I would consider changing the sentence to: 

For instance, algorithms cannot access the internet by default.

2023-07-13 09:46 UTC, frankcorneliusmartin commented on docs/algorithms/develop.rst
> +as `vtg.basic <https://github.com/IKNL/vtg.basic>`_. If you plan to write your
Maybe refer to this template repo instead: https://github.com/IKNL/vtg.tpl

2023-07-13 09:46 UTC, frankcorneliusmartin commented on docs/algorithms/develop.rst
> +The central part is responsible for orchestrating the algorithm and combining
I would use 'aggregate the partial results'.

2023-07-13 12:34 UTC, bartvanb commented on docs/algorithms/concepts.rst
> +analysis.
Good point, I changed the paragraph to something close to your suggestion.

2023-07-13 12:36 UTC, bartvanb commented on docs/algorithms/concepts.rst
> +    information, see `here <https://vantage6.ai/news/algorithm-journey/>`_.
I agree. For now I put it on my documentation TODO list, do you agree that is sufficient for now?

2023-07-13 12:37 UTC, bartvanb commented on docs/algorithms/concepts.rst
Yes, let's discuss this. Then I think it would be good to add before we release v4.0

2023-07-13 12:41 UTC, bartvanb commented on docs/algorithms/concepts.rst
> +internet while they are running.
agreed, changed this

2023-07-13 12:45 UTC, bartvanb commented on docs/algorithms/develop.rst
> +algorithm. Note that the user should also specify the data type of the database
Well caught, the user doesnt have to specify the data type as that is of course specified in the node config. I changed this to reflect that.

2023-07-13 12:46 UTC, bartvanb commented on docs/algorithms/develop.rst
> +Also, note that this only works for CSV files.
Yes I clarified that

2023-07-14 06:48 UTC, frankcorneliusmartin commented on docs/algorithms/concepts.rst
> +    information, see `here <https://vantage6.ai/news/algorithm-journey/>`_.
Yes

2023-07-14 06:57 UTC, frankcorneliusmartin requested changes

2023-07-14 06:57 UTC, frankcorneliusmartin commented on docs/algorithms/concepts.rst
> +Multi-party analyses commonly have an orchestator or aggregator part and a
Usually one container does both the orcastration and aggregation, thus I am not so fond of the word `or` here.

2023-07-14 07:01 UTC, bartvanb commented on docs/algorithms/develop.rst
> +as `vtg.basic <https://github.com/IKNL/vtg.basic>`_. If you plan to write your
Done

2023-07-14 07:06 UTC, bartvanb commented on docs/algorithms/concepts.rst
> +Multi-party analyses commonly have an orchestator or aggregator part and a
I changed the paragraph, using `central` now and explaining that

2023-07-14 07:07 UTC, merged