Feature/added UI permissions to user endpoint
vantage6/vantage6 pull request #783
Opened 2023-07-31 09:37 UTC by bartvanb

This PR adds a few additional details to the user endpoint so that the UI can be more efficient in determining permissions.

2023-08-01 11:51 UTC, frankcorneliusmartin requested changes

2023-08-01 11:51 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/user.py
> +              name: include_ui_permissions
I don't like the name `include_ui_permissions` as this implies these permissions are for the UI. But these are actually backend permissions. I would change this to `include_permissions`.

2023-08-01 11:51 UTC, frankcorneliusmartin commented on vantage6-server/vantage6/server/resource/user.py
> +                default false.
Why make this exclusive to your own user? I get that this is specifically written for the UI, but why limited it? If other users have sufficient permissions this should not be a problem?

2023-08-01 13:09 UTC, bartvanb commented on vantage6-server/vantage6/server/resource/user.py
> +              name: include_ui_permissions
Changed this

2023-08-01 13:28 UTC, frankcorneliusmartin approved these changes
LGTM

2023-08-01 13:35 UTC, merged

2023-09-12 13:36 UTC, frankcorneliusmartin commented
Tested using 

```python
client.request('user/1', method='get', params={'include_permissions': True})
client.request('user/1', method='get')
```

Output seems correct. Related issue: #832