Change/rabbitmq hostname check improved
vantage6/vantage6 pull request #795
Opened 2023-08-18 08:49 UTC by bartvanb

Fix #282 

- Changed configuration structure RabbitMQ so that users can indicate to run it locally
- no longer requiring specific hostname for running locally but any valid docker container name will do
- updated the docs
- updated `vserver new`

2023-09-06 11:15 UTC, frankcorneliusmartin requested changes
Could you take a look at the 'rabbitmq' key and make it more explicit if it is expected or optional? See specific comments

2023-09-06 11:15 UTC, frankcorneliusmartin commented on vantage6/vantage6/cli/rabbitmq/queue_manager.py
> +        self.queue_uri = self.ctx.config.get('rabbitmq').get('uri')
I assume that this class is only invoked when `self.ctx.config.get('rabbitmq')` exists in the config. In that case, change it to:  `self.ctx.config['rabbitmq'].get('uri')` or when this is not the case and a `None` value is acceptable you could do: `self.ctx.config.get('rabbitmq', {}).get('uri')`

2023-09-06 11:15 UTC, frankcorneliusmartin commented on vantage6/vantage6/cli/server.py
> +        Start RabbitMQ message broker as local container - use in development
"only" missing, now it sounds mandatory

2023-09-06 11:15 UTC, frankcorneliusmartin commented on vantage6/vantage6/cli/server.py
> +    rabbit_uri = ctx.config.get('rabbitmq').get('uri')
Same here: `['rabbitmq']` or `('rabbitmq', {}).get(`

2023-09-06 11:15 UTC, frankcorneliusmartin commented on vantage6/vantage6/cli/server.py
> +    rabbit_uri = ctx.config.get('rabbitmq').get('uri') \
And here also

2023-09-08 06:33 UTC, bartvanb commented on vantage6/vantage6/cli/server.py
> +        Start RabbitMQ message broker as local container - use in development
added

2023-09-08 06:38 UTC, bartvanb commented on vantage6/vantage6/cli/rabbitmq/queue_manager.py
> +        self.queue_uri = self.ctx.config.get('rabbitmq').get('uri')
You are right, so I changed it into the ['rabbitmq'] version

2023-09-08 06:38 UTC, bartvanb commented on vantage6/vantage6/cli/server.py
> +    rabbit_uri = ctx.config.get('rabbitmq').get('uri')
Changed to first option as it is guaranteed to exist here

2023-09-08 06:39 UTC, bartvanb commented on vantage6/vantage6/cli/server.py
> +    rabbit_uri = ctx.config.get('rabbitmq').get('uri') \
Here I actually cannot guarantee the key exists, so went for the other variant that guarantees this doesn't crash

2023-09-11 11:39 UTC, frankcorneliusmartin approved these changes
LGTM now

2023-09-11 11:39 UTC, merged