Added initial select_rows preprocessing step and unit test
vantage6/vantage6 pull request #808
Opened 2023-08-31 09:11 UTC by harmbuisman

Initial version of the select_rows functionality that uses a query.

made some changes to mockclient as well, most notably removing the keywords in 
result = method(
                    mock_client=self.parent,
                    mock_data=data,
                    *args, **kwargs
                )
which would otherwise prevent usage of a non-mock method

most other changes to mock_client.py are auto-styling

2023-09-01 14:31 UTC, bartvanb requested changes

2023-09-01 14:31 UTC, bartvanb commented on vantage6-algorithm-tools/vantage6/algorithm/tools/mock_client.py
> +                "organizations": f"/api/organization?collaboration_id={collab_id}",
This is not PEP8, it's above the 80 character limit

2023-09-01 14:31 UTC, bartvanb commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/__init__.py
> +            else list(preprocess_step.keys())[0]
Why would you take the first preprocessing if it hasn't been defined? There is no guarantee that that is what the user wants

2023-09-01 14:31 UTC, bartvanb commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/__init__.py
> +            data = func(data, *parameters)
This might produce results that are different than what the user intended to do, and it could also produce a lot of errors that may not get fed back to the user. I feel that it is better to be strict on the input than run the risk of unexpected results - as long as we give clear errors to the user so they know what to improve.

2023-09-01 14:31 UTC, bartvanb commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/__init__.py
> +            data = func(data, *parameters)
By the way, I notice that we have both been modifying this file - I have done so on branch `feature/preprocessing`. I guess we should merge these changes.

2023-09-01 14:31 UTC, bartvanb commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/functions.py
> +    return df.query(query)
Nice first addition! It already gives a lot of possibilities to expert Python users for filters. For users that are less familiar with pandas, could you also create a few functions that allow them to execute different types of queries? I'm thinking of functions like e.g. only selecting values from a list in a certain column (something like `df.loc[df.some_column.isin(['a', 'b', 'c'])`) and that users only have to provide column name and the list

2023-09-06 09:18 UTC, harmbuisman commented on mock_package/__init__.py
> +    return mock_data[0].to_json()
As dicussed, this is needed by the MockClient module argument, which requires the name of a module that can be imported

2023-09-06 09:18 UTC, harmbuisman commented on vantage6-algorithm-tools/tests/test_preprocessing.py
> +def test_dataframe(n=1000, seed=0):
Adapted

2023-09-06 09:18 UTC, harmbuisman commented on vantage6-algorithm-tools/tests/test_preprocessing.py
> +        input_ = {"method": "execute", "master": True, "kwargs": {}}
Done

2023-09-06 09:18 UTC, harmbuisman commented on vantage6-algorithm-tools/tests/test_preprocessing.py
> +            result = pd.read_json(mockclient.result.get(id_=child_task.get("id") + 1))
Seems the changed fixed it, no longer need the try .. catch

2023-09-06 09:19 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/mock_client.py
> +                "organizations": f"/api/organization?collaboration_id={collab_id}",
Updated the black formatting using a toml file in accordance to line width of 80

2023-09-06 09:19 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/__init__.py
> +            else list(preprocess_step.keys())[0]
I now adapted to follow the strict definition

2023-09-06 09:20 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/__init__.py
> +            data = func(data, *parameters)
Your changes are merged in. I now adapted to the strict preprocessing syntax

2023-09-06 09:20 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/functions.py
> +    return df.query(query)
thx, I now also added column selecting and dropping, row filters not using query on todo

2023-09-06 14:59 UTC, bartvanb requested changes
My main request is if you could add more preprocessing functions, let's talk about that elsewhere

2023-11-02 13:52 UTC, bartvanb requested changes
Great work, I think we'll have a nice set of preprocessing soon. The number of comments is rather large but so is the change - I think most comments are minor or things that we should discuss/think about.

2023-11-02 13:52 UTC, bartvanb commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/encoding.py
> +    2  1.5  2.5
As indicated above, if this said `min_max_scale([ {'min': 0, 'max': 2, 'column': 'a'}, {min: 1, max: 3, column: 'b'}], it would be more readable for me

2023-11-02 13:52 UTC, bartvanb commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/encoding.py
> +) -> pd.DataFrame:
Would it be an idea to call this function `scale_normal_distribution` and the one above `scale_linear` (or something like that)?

2023-11-02 13:52 UTC, bartvanb commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/encoding.py
> +        df_scaled[col] = (df[col] - mean) / std
Maybe add a new column to contain the scaled data

2023-11-02 13:52 UTC, bartvanb commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/encoding.py
> +
I would never have thought of this preprocessing but I like it :-)

2023-11-02 13:52 UTC, bartvanb commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/encoding.py
> +    3  (50, 60]
Do we currently have another preprocessing function with which we could transform `Age = (20, 30]` to something like `older_than = 20` and `younger_than = 30`?

2023-11-02 13:52 UTC, bartvanb commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/encoding.py
> +        "most_frequent", and "constant".
We should have a list of all options that we allow

2023-11-02 13:52 UTC, bartvanb commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/encoding.py
> +    4  5.0  3.5  3.0
The example for column A confused me :-) maybe something where it doesn't look like it fulfills the row?

2023-11-02 13:52 UTC, bartvanb commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/filtering.py
> +        The maximum value to filter on, by default None.
I think this value will also be shown as `min_` in the UI where it would be nicer to get rid of the underscore somehow

2023-11-07 09:38 UTC, harmbuisman commented on mock_package/__init__.py
> +    return mock_data.to_json()
mockclient = MockAlgorithmClient(
             datasets=datasets, module="mock_package"
       )

it is read by the mockclient. Will it be found if it is put in the above directory?

2023-11-07 09:40 UTC, harmbuisman commented on vantage6-algorithm-tools/tests/__init__.py
It is needed by unittest for test discovery

2023-11-07 09:44 UTC, harmbuisman commented on vantage6-algorithm-tools/tests/test_docker_wrapper.py
#933

2023-11-07 09:48 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/aggregation.py
> +    ],
Nice, wasn't aware

2023-11-07 10:19 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/__init__.py
> +        data = func(data, **parameters)
Catch and enrich with additional information

2023-11-07 10:21 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/column.py
> +        number of columns.
remove. also remove all operations that operate on index due to not being sure about table order across the nodes.

2023-11-07 10:26 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/datetime.py
> +    new_df = df.copy()
To be evaluated, one other option is to do a copy at the start of the preprocessing. Question though is if all the functions should then return a df or just adapt the input inplace

2023-11-07 10:31 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/datetime.py
> +        String input to be converted to datetime if `column` is None.
Remove here as the timedelta already supports to input a constant reference date.

2023-11-07 10:35 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/datetime.py
> +    2   3 days     3 days
other function has a simpler interface (not fmt etc.)

2023-11-07 10:42 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/encoding.py
> +    2  1.5  2.5
Pending. Problem with dictionary is that there can be a huge amount of features, which is cumbersome to specify in the UI.

2023-11-07 10:46 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/encoding.py
> +) -> pd.DataFrame:
current interface follows scikit-learn (sklearn) names

2023-11-07 10:47 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/encoding.py
> +        df_scaled[col] = (df[col] - mean) / std
typically not a common use case to preserve both, due to model performance needing the scaling

2023-11-07 10:48 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/encoding.py
> +    3  (50, 60]
the assign can be used

2023-11-07 10:49 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/encoding.py
> +    4  5.0  3.5  3.0
adapt example because it looks like interpolation rather than imputation

2023-11-07 10:51 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/filtering.py
> +        A list of indices or slice-strings specifying the columns to extract.
As dicussed earlier, we should not allow index slicing due to not being sure about order of columns across nodes

2023-11-07 10:52 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/filtering.py
> +        The maximum value to filter on, by default None.
min_value, max_value

2023-11-07 10:52 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/filtering.py
> +def select_columns(df: pd.DataFrame, columns: list) -> pd.DataFrame:
yes, needed to prepare the exact df that the model trains/predicts on

2023-11-08 03:07 UTC, harmbuisman commented on pyproject.toml
> +'''
It may be possible to merge the following into the toml file:
.coveragerc - Configuration for pytest and coverage can sometimes be included in the pyproject.toml file under tool-specific tables if the tools support it.

.readthedocs.yml - Read the Docs has started to support configuration via the pyproject.toml file, so this could potentially be included depending on the specifics of your documentation.

As these do not cover functionalities in the scope of this change I'll leave merging them as something to consider

2023-11-08 08:40 UTC, harmbuisman commented on vantage6-algorithm-tools/tests/test_preprocessing.py
> +        "PhD": 4,
There is no link required between data generation and the preprocessing operations, so the different uses are separate.

2023-11-08 08:47 UTC, harmbuisman commented on vantage6-algorithm-tools/tests/test_preprocessing.py
> +):
To cover multiple scenarios for what a researcher may need in terms of processing.

2023-11-08 08:57 UTC, harmbuisman commented on vantage6-algorithm-tools/tests/test_preprocessing.py
> +                            "parameters": {"columns": [0, 1, 2, 3]},
Ok, will remove

2023-11-08 09:09 UTC, harmbuisman commented on vantage6-algorithm-tools/tests/test_preprocessing.py
> +                                    "medication",
Each of the functions has doctests that only tests that specific function. I think that should cover the functions. The doctests can be easily extended.
I see your point regarding the failed test and having to debug the test. 
The batch tests serve to test preprocessing within the preprocessing handling of the mockclient, which is a bit different than the doctests, which is unittest on the function.
The batch tests also serve as examples. I mentioned that in the docs, but perhaps we can even host them automatically on the docs?

2023-11-08 09:13 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/mock_client.py
> +                client_copy.organization_id = org_id
Something went wrong in the merge :) Will remove

2023-11-08 09:21 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/__init__.py
> +func_dict = {f.__name__: f for f in funcs}
Very nice suggestion. I adapted a bit to check against imported functions since getmembers includes those as well.

2023-11-08 09:23 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/__init__.py
> +__all__ = list(func_dict.keys())
This is for the developer to be able to do vantage6.algorithm.tools.preprocessing.function_name. WIll add the comment

2023-11-08 09:25 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/aggregation.py
> +  allows for customization of the prefix used in the resulting column names.
Ok!

2023-11-08 10:16 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/aggregation.py
> +    ],
Updated

2023-11-08 10:33 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/aggregation.py
> +            * to concatenate strings: lambda x: ''.join(x)
removed the lambda, added the internals as string

2023-11-08 10:34 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/aggregation.py
> +    ...     'ag': ['young', 'young', 'old', 'old'],
the problem is that the names then become too long for the result dataframe to be printed on a single line

2023-11-08 10:47 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/datetime.py
> +        Output column name when `input_value` is used.
This will likely be used as a type conversion, I see no use case for keeping a string date

2023-11-08 10:50 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/datetime.py
> +        new_df[output_column] = pd.to_timedelta(duration, errors=errors)
updated the logic

2023-11-08 10:50 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/datetime.py
> +    2   3 days   2 days
as discussed in the call. It is to convert a string to the timedelta type

2023-11-08 10:50 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/datetime.py
> +    dates = pd.to_datetime(df[column], format=fmt)
to_datetime already has a good one

2023-11-08 13:06 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/encoding.py
> +        min_vals and max_vals must match df.columns.
For the UI it may be better indeed, but in this case the type of input is non-conventional, it would be a list of conversion parameters with non-unique type str->float, str->float, str->str. Perhaps it would be better to then add a separate UI method that converts input as suggested to the provided input.

2023-11-08 13:07 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/encoding.py
> +standard deviations for scaling operations.
may make sense indeed, scalers are not really encoders, although all preprocessings are transformations. perhaps there is an alternative better name

2023-11-08 13:09 UTC, harmbuisman commented on vantage6-algorithm-tools/vantage6/algorithm/tools/preprocessing/encoding.py
> +    2  1.5  2.5
After additional thought it seems too unconventional as a function signature. This is a list of parameters. Would be more suitable for a wrapper interface instead.

2024-04-09 11:08 UTC, bartvanb commented
This implementation is stalled - we have new ideas on how preprocessing will work, see #943

2025-01-23 15:22 UTC, closed without merging