Feature/extemding wrapper for omop
vantage6/vantage6 pull request #885
Opened 2023-10-03 07:39 UTC by frankcorneliusmartin

Could we merge this part now? That way we can start using the OMOP base image for creating algorithms. Dont delete the branch.

2023-10-03 11:51 UTC, bartvanb requested changes

2023-10-03 11:51 UTC, bartvanb commented on docker/algorithm-base.Dockerfile
> +FROM python:3.11-slim-bullseye
If we do this, we need to modify the docs that algorithms should be written in python 3.11.
Also, what's the diff between bullseye and buster?

2023-10-03 11:51 UTC, bartvanb commented on docker/algorithm-base.Dockerfile
> +# install dependencies for the ohdsi tools part of the wrapper
This comment seems not to belong?

2023-10-03 11:51 UTC, bartvanb commented on docker/algorithm-omop-base.Dockerfile
> +ENV LD_LIBRARY_PATH=/usr/lib/jvm/java-17-openjdk-amd64/lib/server/
Maybe you could add a comment what this does

2023-10-05 09:06 UTC, frankcorneliusmartin commented on docker/algorithm-base.Dockerfile
> +FROM python:3.11-slim-bullseye
That is the version of the Debian distribution. I needed this for some R / Java related dependency. This OS version change should not affect algorithms. 

I will check if it also works with python:3.10, else I will update the docs.

2023-10-05 11:02 UTC, frankcorneliusmartin commented on docker/algorithm-omop-base.Dockerfile
> +ENV LD_LIBRARY_PATH=/usr/lib/jvm/java-17-openjdk-amd64/lib/server/
I added a comment and a fixme, as this is not such a great solution. However i also do not know how with deal with this properly.

2023-10-05 11:02 UTC, frankcorneliusmartin commented on docker/algorithm-base.Dockerfile
> +# install dependencies for the ohdsi tools part of the wrapper
Yes you ar right.

2023-10-05 11:05 UTC, frankcorneliusmartin commented on docker/algorithm-base.Dockerfile
> +FROM python:3.11-slim-bullseye
I ended up reverting to `3.10` just to avoid compatibility issues

2023-10-05 12:19 UTC, bartvanb commented on docker/algorithm-base.Dockerfile
> +FROM python:3.11-slim-bullseye
Clear!

2023-10-05 12:20 UTC, bartvanb approved these changes

2023-10-05 12:20 UTC, merged