Feature/extemding wrapper for omop
vantage6/vantage6 pull request #902
Opened 2023-10-17 09:45 UTC by frankcorneliusmartin

2023-10-17 11:51 UTC, frankcorneliusmartin commented
## Codacy issues
1. Outdated linter https://stackoverflow.com/questions/72732058/match-case-invalid-syntax-with-spyder
2. And some `pip install ...` without pinned version, this is intentional for now

2023-10-17 14:53 UTC, bartvanb requested changes
looks good, small changes

2023-10-17 14:53 UTC, bartvanb commented on docker/algorithm-ohdsi-base.Dockerfile
> +# ARG OHDSI_VERSION=0.3.2
should we remove this?

2023-10-17 14:53 UTC, bartvanb commented on docker/algorithm-ohdsi-base.Dockerfile
> +# ARG OHDSI_VERSION=0.3.2
and line 7 as well? Or why not?

2023-10-17 14:53 UTC, bartvanb commented on docs/node/node_config.yaml
> +# the `database` settings.
Can we keep the original example here? Also, the sentence you added is not entirely clear to me: which `env` key and which database settings? Can you be more specific?

2023-10-17 14:53 UTC, bartvanb commented on docs/node/node_config.yaml
> +# the `database` settings.
Right, I see now that these are added below. In that case, maybe we restore this to original as I think that's clearer: when the example for OMOP is already there, it's obvious not to use this for OMOP

2023-10-17 14:53 UTC, bartvanb commented on vantage6-algorithm-tools/vantage6/algorithm/tools/decorators.py
> +    By adding `@data` to a function, one or several pandas dataframes will be
This should actually be `@data()`

2023-10-17 14:53 UTC, bartvanb commented on vantage6-algorithm-tools/vantage6/algorithm/tools/decorators.py
> +    By adding `@data` to a function, one or several pandas dataframes will be
or with `N` inside the parentheses

2023-10-17 14:53 UTC, bartvanb commented on vantage6-algorithm-tools/vantage6/algorithm/tools/decorators.py
> +                case "OMOP":
maybe case insentivity would be nice

2023-10-17 14:53 UTC, bartvanb commented on vantage6-algorithm-tools/vantage6/algorithm/tools/decorators.py
> +              "build this algorithm?")
Would be nice to specify which one they should use

2023-10-17 14:53 UTC, bartvanb commented on vantage6-algorithm-tools/vantage6/algorithm/tools/decorators.py
> +    if "USER" not in os.environ or "PASSWORD" not in os.environ:
I prefer splitting these into separate `if`s because then the user doesn't have to guess what they are missing

2023-10-17 14:53 UTC, bartvanb commented on vantage6-node/vantage6/node/docker/task_manager.py
> +                    environment_variables[key.upper()] = db['env'][key]
This is a bit tricky - should we worry that people can overwrite other envvars in this way? We could work with an include list instead of doing everything (but I see the chances are small)

2023-10-17 14:58 UTC, frankcorneliusmartin commented on docker/algorithm-ohdsi-base.Dockerfile
> +# ARG OHDSI_VERSION=0.3.2
Added a note why I kept that

2023-10-18 06:59 UTC, bartvanb commented on vantage6-node/vantage6/node/docker/task_manager.py
> +                    environment_variables[key.upper()] = db['env'][key]
Yes sounds good! I do feel like we may be able to think of something more specific than `SPECIAL`, e.g. something like `DB_PARAM`. But then again, `SPECIAL` also indicates such cases nicely, although then we should be sure to make clear in the comments/user feedback what this is and why they cannot use it. So let's use `SPECIAL` with good comments?

2023-10-18 07:34 UTC, frankcorneliusmartin commented on vantage6-node/vantage6/node/docker/task_manager.py
> +                    environment_variables[key.upper()] = db['env'][key]
Done, i prefixed them with `DB_PARAM` 👍

2023-10-18 12:17 UTC, bartvanb commented on vantage6-algorithm-tools/vantage6/algorithm/tools/decorators.py
> +        True.
I'm not too familiar with OMOP, but usually I wouldn't expect to need this metadata in an algorithm for a SQL DB. Just to check: do you think the majority of algorithms will need this?

2023-10-18 12:19 UTC, bartvanb commented on vantage6-algorithm-tools/vantage6/algorithm/tools/decorators.py
> +def metadata(func: callable, *args, **kwargs) -> callable:
I could be wrong, but I wouldn't expect the arguments here - then calling it would be `@metadata(func, ...)` right?

2023-10-18 12:23 UTC, bartvanb commented on vantage6-algorithm-tools/vantage6/algorithm/tools/decorators.py
> +    password = os.environ[f"{label_}_DB_PARAM_PASSWORD"]
I would have a slight preference to change `{label}_DB_PARAM` into `DB_PARAM_{label}` because then all the 'special' envvars start with the same prefix. If you disagree, feel free to leave as is

2023-10-18 12:26 UTC, bartvanb commented on vantage6-algorithm-tools/vantage6/algorithm/tools/decorators.py
> +def metadata(func: callable, *args, **kwargs) -> callable:
Also, as this decorator has now changed, shouldn't that lead to a docs update?

2023-10-18 12:30 UTC, frankcorneliusmartin commented on vantage6-algorithm-tools/vantage6/algorithm/tools/decorators.py
> +        True.
In the OMOP case, yes. As many of the OHDSI function that we use in the algorithm need certain settings that are in this metadata. That is why I set it to default to `True`. In light of adding different connections this might get inconvenient? Let me know.

2023-10-18 12:54 UTC, frankcorneliusmartin commented on vantage6-algorithm-tools/vantage6/algorithm/tools/decorators.py
> +def metadata(func: callable, *args, **kwargs) -> callable:
> I could be wrong, but I wouldn't expect the arguments here - then calling it would be `@metadata(func, ...)` right?

Yes, that was a remainder of the change. I removed them. 



> Also, as this decorator has now changed, shouldn't that lead to a docs update?

I tried to get away with the fact that is was documented in the `function-docs`. I added a section in `Implementing the algorithm functions`

2023-10-18 12:55 UTC, frankcorneliusmartin commented on vantage6-algorithm-tools/vantage6/algorithm/tools/decorators.py
> +    password = os.environ[f"{label_}_DB_PARAM_PASSWORD"]
I did this do be consistent with the `*_DATABASE_URI` now all settings are per database grouped. I think this is also nice since these are database dependent. So I am going to leave it like this.

2023-10-18 13:00 UTC, bartvanb approved these changes

2023-10-18 13:36 UTC, merged