Clarified and fixed errors in docstrings of algorithmClient functions…
vantage6/vantage6 pull request #905
Opened 2023-10-17 13:30 UTC by bartvanb

Fix #900

2023-10-18 13:11 UTC, frankcorneliusmartin requested changes

2023-10-18 13:11 UTC, frankcorneliusmartin commented on vantage6-algorithm-tools/vantage6/algorithm/client/__init__.py
> +                additional data to identify them. If obtaining
Maybe its good to mention that one algorithm could have multiple addresses and that therefor the additional data is required. Now it still seems a bit vague to me. (Maybe put this in the body and not in the return type)

2023-10-18 13:11 UTC, frankcorneliusmartin commented on vantage6-algorithm-tools/vantage6/algorithm/client/__init__.py
> +        # evaluate what is most effective though complete
In that case this function should have an adduitional argument `label` as well.

2023-10-18 13:11 UTC, frankcorneliusmartin commented on vantage6-algorithm-tools/vantage6/algorithm/client/__init__.py
> +                additional data to identify them. If obtaining
Same goes for the very similar docstrings

2023-10-18 15:20 UTC, bartvanb commented on vantage6-algorithm-tools/vantage6/algorithm/client/__init__.py
> +        # evaluate what is most effective though complete
Yes indeed. This was to address a question by Harm that he expected a string to be returned for a function with this name. I can see that the dictionary is bloated now, maybe we can get away with just `ip, port, label` and maybe `node_id` or `organization_id`. But I guess that would also be v5

2023-10-19 09:13 UTC, bartvanb commented on vantage6-algorithm-tools/vantage6/algorithm/client/__init__.py
> +                additional data to identify them. If obtaining
Changed them again

2023-10-19 09:14 UTC, bartvanb commented on vantage6-algorithm-tools/vantage6/algorithm/client/__init__.py
> +        # evaluate what is most effective though complete
removed this now: the new docstrings should be clear enough on what to expect - and Harm indicated this was the main ponit.

2023-10-19 09:41 UTC, frankcorneliusmartin approved these changes
LGTM

2023-10-19 09:41 UTC, merged