Set READTHEDOCS environment variable for the 'make devdocs' target
vantage6/vantage6 pull request #927
Opened 2023-11-02 07:40 UTC by bartvanb

2023-12-04 15:21 UTC, frankcorneliusmartin requested changes

2023-12-04 15:21 UTC, frankcorneliusmartin commented on Makefile
> +devdocs: export READTHEDOCS = Yes
This does not seem legit. It seems you are redefining `devdocs`. Also does this work on windows?

2023-12-05 15:53 UTC, bartvanb commented on Makefile
> +devdocs: export READTHEDOCS = Yes
As discussed, this works for me (although it looks weird). Consensus is that Frank should try if it works for him locally, then we merge it

2024-01-16 14:30 UTC, frankcorneliusmartin approved these changes
LGTM

2024-01-16 14:30 UTC, merged