Docs/emphasize private docker registry importance
vantage6/vantage6 pull request #977
Opened 2024-01-12 15:14 UTC by bartvanb

2024-01-16 14:22 UTC, frankcorneliusmartin requested changes

2024-01-16 14:22 UTC, frankcorneliusmartin commented on docs/server/optional.rst
> +Harbor
Maybe good that we recommend this.

2024-01-17 13:39 UTC, bartvanb commented on docs/server/optional.rst
> +  private registry.
I added this, but not here in the header but below in the Docker Hub section.

2024-01-17 15:18 UTC, frankcorneliusmartin approved these changes

2024-01-17 15:18 UTC, merged